/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddOnEnvironmentVariable } from './add-on-environment-variable';
// May contain unused imports in some cases
// @ts-ignore
import { AddOnSecretPropagation } from './add-on-secret-propagation';

/**
 * Representation of an add-on config. The attributes under it are to be used by the addon once its installed in the cluster.
 * @export
 * @interface AddOnConfig
 */
export interface AddOnConfig {
    /**
     * Indicates the type of this object. Will be \'AddOnConfig\' if this is a complete object or \'AddOnConfigLink\' if it is just a link.
     * @type {string}
     * @memberof AddOnConfig
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof AddOnConfig
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof AddOnConfig
     */
    'href'?: string;
    /**
     * List of environment variables for the addon
     * @type {Array<AddOnEnvironmentVariable>}
     * @memberof AddOnConfig
     */
    'add_on_environment_variables'?: Array<AddOnEnvironmentVariable>;
    /**
     * List of secret propagations for the addon
     * @type {Array<AddOnSecretPropagation>}
     * @memberof AddOnConfig
     */
    'secret_propagations'?: Array<AddOnSecretPropagation>;
}

