/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddOnRequirement } from './add-on-requirement';

/**
 * Representation of an add-on parameter option.
 * @export
 * @interface AddOnParameterOption
 */
export interface AddOnParameterOption {
    /**
     * Name of the add-on parameter option.
     * @type {string}
     * @memberof AddOnParameterOption
     */
    'name'?: string;
    /**
     * Rank of option to be used in cases where editable direction should be restricted.
     * @type {number}
     * @memberof AddOnParameterOption
     */
    'rank'?: number;
    /**
     * List of add-on requirements for this parameter option.
     * @type {Array<AddOnRequirement>}
     * @memberof AddOnParameterOption
     */
    'requirements'?: Array<AddOnRequirement>;
    /**
     * Value of the add-on parameter option.
     * @type {string}
     * @memberof AddOnParameterOption
     */
    'value'?: string;
}

