/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddOn } from './add-on';
// May contain unused imports in some cases
// @ts-ignore
import { AddOnInstallationBilling } from './add-on-installation-billing';
// May contain unused imports in some cases
// @ts-ignore
import { AddOnInstallationParameter } from './add-on-installation-parameter';
// May contain unused imports in some cases
// @ts-ignore
import { AddOnInstallationState } from './add-on-installation-state';
// May contain unused imports in some cases
// @ts-ignore
import { AddOnVersion } from './add-on-version';

/**
 * Representation of an add-on installation in a cluster.
 * @export
 * @interface AddOnInstallation
 */
export interface AddOnInstallation {
    /**
     * Indicates the type of this object. Will be \'AddOnInstallation\' if this is a complete object or \'AddOnInstallationLink\' if it is just a link.
     * @type {string}
     * @memberof AddOnInstallation
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof AddOnInstallation
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof AddOnInstallation
     */
    'href'?: string;
    /**
     * 
     * @type {AddOn}
     * @memberof AddOnInstallation
     */
    'addon'?: AddOn;
    /**
     * 
     * @type {AddOnVersion}
     * @memberof AddOnInstallation
     */
    'addon_version'?: AddOnVersion;
    /**
     * 
     * @type {AddOnInstallationBilling}
     * @memberof AddOnInstallation
     */
    'billing'?: AddOnInstallationBilling;
    /**
     * Date and time when the add-on was initially installed in the cluster.
     * @type {string}
     * @memberof AddOnInstallation
     */
    'creation_timestamp'?: string;
    /**
     * Version of the operator installed by the add-on.
     * @type {string}
     * @memberof AddOnInstallation
     */
    'operator_version'?: string;
    /**
     * List of add-on parameters for this add-on installation.
     * @type {Array<AddOnInstallationParameter>}
     * @memberof AddOnInstallation
     */
    'parameters'?: Array<AddOnInstallationParameter>;
    /**
     * 
     * @type {AddOnInstallationState}
     * @memberof AddOnInstallation
     */
    'state'?: AddOnInstallationState;
    /**
     * Reason for the current State.
     * @type {string}
     * @memberof AddOnInstallation
     */
    'state_description'?: string;
    /**
     * Date and time when the add-on installation information was last updated.
     * @type {string}
     * @memberof AddOnInstallation
     */
    'updated_timestamp'?: string;
}



