/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddOnNamespace
 */
export interface AddOnNamespace {
    /**
     * Indicates the type of this object. Will be \'AddOnNamespace\' if this is a complete object or \'AddOnNamespaceLink\' if it is just a link.
     * @type {string}
     * @memberof AddOnNamespace
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof AddOnNamespace
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof AddOnNamespace
     */
    'href'?: string;
    /**
     * Annotations to be applied to this namespace.
     * @type {{ [key: string]: string; }}
     * @memberof AddOnNamespace
     */
    'annotations'?: { [key: string]: string; };
    /**
     * Labels to be applied to this namespace.
     * @type {{ [key: string]: string; }}
     * @memberof AddOnNamespace
     */
    'labels'?: { [key: string]: string; };
    /**
     * Name of the namespace.
     * @type {string}
     * @memberof AddOnNamespace
     */
    'name'?: string;
}

