/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BillingModel } from './billing-model';

/**
 * Representation of an add-on installation billing.
 * @export
 * @interface AddOnInstallationBilling
 */
export interface AddOnInstallationBilling {
    /**
     * Indicates the type of this object. Will be \'AddOnInstallationBilling\' if this is a complete object or \'AddOnInstallationBillingLink\' if it is just a link.
     * @type {string}
     * @memberof AddOnInstallationBilling
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof AddOnInstallationBilling
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof AddOnInstallationBilling
     */
    'href'?: string;
    /**
     * Account ID for billing market place
     * @type {string}
     * @memberof AddOnInstallationBilling
     */
    'billing_marketplace_account'?: string;
    /**
     * 
     * @type {BillingModel}
     * @memberof AddOnInstallationBilling
     */
    'billing_model'?: BillingModel;
}



