/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Temporary administrator credentials generated during the installation of the cluster.
 * @export
 * @interface AdminCredentials
 */
export interface AdminCredentials {
    /**
     * Cluster administrator password.
     * @type {string}
     * @memberof AdminCredentials
     */
    'password'?: string;
    /**
     * Cluster administrator user name.
     * @type {string}
     * @memberof AdminCredentials
     */
    'user'?: string;
}

