/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AlertInfo } from './alert-info';

/**
 * Provides information about the alerts firing on the cluster.
 * @export
 * @interface AlertsInfo
 */
export interface AlertsInfo {
    /**
     * 
     * @type {Array<AlertInfo>}
     * @memberof AlertsInfo
     */
    'alerts'?: Array<AlertInfo>;
}

