/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EncryptionKey } from './encryption-key';

/**
 * 
 * @export
 * @interface ApiClustersMgmtV1GcpInquiriesEncryptionKeysPost200Response
 */
export interface ApiClustersMgmtV1GcpInquiriesEncryptionKeysPost200Response {
    /**
     * Retrieved list of encryption keys.
     * @type {Array<EncryptionKey>}
     * @memberof ApiClustersMgmtV1GcpInquiriesEncryptionKeysPost200Response
     */
    'items'?: Array<EncryptionKey>;
    /**
     * Index of the returned page, where one corresponds to the first page. As this collection doesn\'t support paging the result will always be `1`.
     * @type {number}
     * @memberof ApiClustersMgmtV1GcpInquiriesEncryptionKeysPost200Response
     */
    'page'?: number;
    /**
     * Number of items that will be contained in the returned page. As this collection doesn\'t support paging or searching the result will always be the total number of regions of the provider.
     * @type {number}
     * @memberof ApiClustersMgmtV1GcpInquiriesEncryptionKeysPost200Response
     */
    'size'?: number;
    /**
     * Total number of items of the collection that match the search criteria, regardless of the size of the page. As this collection doesn\'t support paging or searching the result will always be the total number of available regions of the provider.
     * @type {number}
     * @memberof ApiClustersMgmtV1GcpInquiriesEncryptionKeysPost200Response
     */
    'total'?: number;
}

