/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { KeyRing } from './key-ring';

/**
 * 
 * @export
 * @interface ApiClustersMgmtV1GcpInquiriesKeyRingsPost200Response
 */
export interface ApiClustersMgmtV1GcpInquiriesKeyRingsPost200Response {
    /**
     * Retrieved list of key rings.
     * @type {Array<KeyRing>}
     * @memberof ApiClustersMgmtV1GcpInquiriesKeyRingsPost200Response
     */
    'items'?: Array<KeyRing>;
    /**
     * Index of the returned page, where one corresponds to the first page. As this collection doesn\'t support paging the result will always be `1`.
     * @type {number}
     * @memberof ApiClustersMgmtV1GcpInquiriesKeyRingsPost200Response
     */
    'page'?: number;
    /**
     * Number of items that will be contained in the returned page. As this collection doesn\'t support paging or searching the result will always be the total number of key rings of the provider.
     * @type {number}
     * @memberof ApiClustersMgmtV1GcpInquiriesKeyRingsPost200Response
     */
    'size'?: number;
    /**
     * Total number of items of the collection that match the search criteria, regardless of the size of the page. As this collection doesn\'t support paging or searching the result will always be the total number of available key rings of the provider.
     * @type {number}
     * @memberof ApiClustersMgmtV1GcpInquiriesKeyRingsPost200Response
     */
    'total'?: number;
}

