/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { VersionGate } from './version-gate';

/**
 * 
 * @export
 * @interface ApiClustersMgmtV1VersionGatesGet200Response
 */
export interface ApiClustersMgmtV1VersionGatesGet200Response {
    /**
     * Retrieved list of version gates.
     * @type {Array<VersionGate>}
     * @memberof ApiClustersMgmtV1VersionGatesGet200Response
     */
    'items'?: Array<VersionGate>;
    /**
     * Index of the requested page, where one corresponds to the first page.
     * @type {number}
     * @memberof ApiClustersMgmtV1VersionGatesGet200Response
     */
    'page'?: number;
    /**
     * Maximum number of items that will be contained in the returned page.  Default value is `100`.
     * @type {number}
     * @memberof ApiClustersMgmtV1VersionGatesGet200Response
     */
    'size'?: number;
    /**
     * Total number of items of the collection that match the search criteria, regardless of the size of the page.
     * @type {number}
     * @memberof ApiClustersMgmtV1VersionGatesGet200Response
     */
    'total'?: number;
}

