/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ResourceRange } from './resource-range';

/**
 * 
 * @export
 * @interface AutoscalerResourceLimitsGPULimit
 */
export interface AutoscalerResourceLimitsGPULimit {
    /**
     * 
     * @type {ResourceRange}
     * @memberof AutoscalerResourceLimitsGPULimit
     */
    'range'?: ResourceRange;
    /**
     * The type of GPU to associate with the minimum and maximum limits. This value is used by the Cluster Autoscaler to identify Nodes that will have GPU capacity by searching for it as a label value on the Node objects. For example, Nodes that carry the label key `cluster-api/accelerator` with the label value being the same as the Type field will be counted towards the resource limits by the Cluster Autoscaler.
     * @type {string}
     * @memberof AutoscalerResourceLimitsGPULimit
     */
    'type'?: string;
}

