/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of aws node pool specific parameters.
 * @export
 * @interface AWSNodePool
 */
export interface AWSNodePool {
    /**
     * Indicates the type of this object. Will be \'AWSNodePool\' if this is a complete object or \'AWSNodePoolLink\' if it is just a link.
     * @type {string}
     * @memberof AWSNodePool
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof AWSNodePool
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof AWSNodePool
     */
    'href'?: string;
    /**
     * InstanceProfile is the AWS EC2 instance profile, which is a container for an IAM role that the EC2 instance uses.
     * @type {string}
     * @memberof AWSNodePool
     */
    'instance_profile'?: string;
    /**
     * InstanceType is an ec2 instance type for node instances (e.g. m5.large).
     * @type {string}
     * @memberof AWSNodePool
     */
    'instance_type'?: string;
    /**
     * Optional keys and values that the installer will add as tags to all AWS resources it creates
     * @type {{ [key: string]: string; }}
     * @memberof AWSNodePool
     */
    'tags'?: { [key: string]: string; };
}

