/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Spot market options for AWS machine pool.
 * @export
 * @interface AWSSpotMarketOptions
 */
export interface AWSSpotMarketOptions {
    /**
     * Indicates the type of this object. Will be \'AWSSpotMarketOptions\' if this is a complete object or \'AWSSpotMarketOptionsLink\' if it is just a link.
     * @type {string}
     * @memberof AWSSpotMarketOptions
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof AWSSpotMarketOptions
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof AWSSpotMarketOptions
     */
    'href'?: string;
    /**
     * The max price for spot instance. Optional. If not set, use the on-demand price.
     * @type {number}
     * @memberof AWSSpotMarketOptions
     */
    'max_price'?: number;
}

