/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * BillingModelItem represents a billing model
 * @export
 * @interface BillingModelItem
 */
export interface BillingModelItem {
    /**
     * Indicates the type of this object. Will be \'BillingModelItem\' if this is a complete object or \'BillingModelItemLink\' if it is just a link.
     * @type {string}
     * @memberof BillingModelItem
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof BillingModelItem
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof BillingModelItem
     */
    'href'?: string;
    /**
     * BillingModelType is the type of the BillingModel. e.g. standard, marketplace.
     * @type {string}
     * @memberof BillingModelItem
     */
    'billing_model_type'?: string;
    /**
     * Single line description of the billing model.
     * @type {string}
     * @memberof BillingModelItem
     */
    'description'?: string;
    /**
     * User friendly display name of the billing model.
     * @type {string}
     * @memberof BillingModelItem
     */
    'display_name'?: string;
    /**
     * Indicates the marketplace of the billing model. e.g. gcp, aws, etc.
     * @type {string}
     * @memberof BillingModelItem
     */
    'marketplace'?: string;
}

