/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CCS
 */
export interface CCS {
    /**
     * Indicates the type of this object. Will be \'CCS\' if this is a complete object or \'CCSLink\' if it is just a link.
     * @type {string}
     * @memberof CCS
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof CCS
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof CCS
     */
    'href'?: string;
    /**
     * Indicates if cloud permissions checks are disabled, when attempting installation of the cluster.
     * @type {boolean}
     * @memberof CCS
     */
    'disable_scp_checks'?: boolean;
    /**
     * Indicates if Customer Cloud Subscription is enabled on the cluster.
     * @type {boolean}
     * @memberof CCS
     */
    'enabled'?: boolean;
}

