/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AWS } from './aws';
// May contain unused imports in some cases
// @ts-ignore
import { CloudRegion } from './cloud-region';
// May contain unused imports in some cases
// @ts-ignore
import { GCP } from './gcp';
// May contain unused imports in some cases
// @ts-ignore
import { Version } from './version';

/**
 * Description of a cloud provider data used for cloud provider inquiries.
 * @export
 * @interface CloudProviderData
 */
export interface CloudProviderData {
    /**
     * 
     * @type {AWS}
     * @memberof CloudProviderData
     */
    'aws'?: AWS;
    /**
     * 
     * @type {GCP}
     * @memberof CloudProviderData
     */
    'gcp'?: GCP;
    /**
     * Availability zone
     * @type {Array<string>}
     * @memberof CloudProviderData
     */
    'availability_zones'?: Array<string>;
    /**
     * Key location
     * @type {string}
     * @memberof CloudProviderData
     */
    'key_location'?: string;
    /**
     * Key ring name
     * @type {string}
     * @memberof CloudProviderData
     */
    'key_ring_name'?: string;
    /**
     * 
     * @type {CloudRegion}
     * @memberof CloudProviderData
     */
    'region'?: CloudRegion;
    /**
     * Subnets
     * @type {Array<string>}
     * @memberof CloudProviderData
     */
    'subnets'?: Array<string>;
    /**
     * 
     * @type {Version}
     * @memberof CloudProviderData
     */
    'version'?: Version;
}

