/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Subnetwork } from './subnetwork';

/**
 * Description of a cloud provider virtual private cloud.
 * @export
 * @interface CloudVPC
 */
export interface CloudVPC {
    /**
     * List of AWS subnetworks with details.
     * @type {Array<Subnetwork>}
     * @memberof CloudVPC
     */
    'aws_subnets'?: Array<Subnetwork>;
    /**
     * CIDR block of the virtual private cloud.
     * @type {string}
     * @memberof CloudVPC
     */
    'cidr_block'?: string;
    /**
     * ID of virtual private cloud.
     * @type {string}
     * @memberof CloudVPC
     */
    'id'?: string;
    /**
     * Name of virtual private cloud according to its `Name` tag on AWS.
     * @type {string}
     * @memberof CloudVPC
     */
    'name'?: string;
    /**
     * List of subnets used by the virtual private cloud.
     * @type {Array<string>}
     * @memberof CloudVPC
     */
    'subnets'?: Array<string>;
}

