/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Registration of a new cluster to the service.  For example, to register a cluster that has been provisioned outside of this service, send a a request like this:  ```http POST /api/clusters_mgmt/v1/register_cluster HTTP/1.1 ```  With a request body like this:  ```json {   \"external_id\": \"d656aecf-11a6-4782-ad86-8f72638449ba\",   \"subscription_id\": \"...\",   \"organization_id\": \"...\" } ```
 * @export
 * @interface ClusterRegistration
 */
export interface ClusterRegistration {
    /**
     * Optional Console URL of the cluster.
     * @type {string}
     * @memberof ClusterRegistration
     */
    'console_url'?: string;
    /**
     * Identifier of the cluster generated by the installer.
     * @type {string}
     * @memberof ClusterRegistration
     */
    'external_id'?: string;
    /**
     * Organization identifier of the cluster generated by the account manager.
     * @type {string}
     * @memberof ClusterRegistration
     */
    'organization_id'?: string;
    /**
     * Subscription identifier of the cluster generated by the account manager.
     * @type {string}
     * @memberof ClusterRegistration
     */
    'subscription_id'?: string;
}

