/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Definition of a cluster link.
 * @export
 * @interface ClusterLink
 */
export interface ClusterLink {
    /**
     * HREF for the cluster, filled in response.
     * @type {string}
     * @memberof ClusterLink
     */
    'href'?: string;
    /**
     * The cluster\'s ID.
     * @type {string}
     * @memberof ClusterLink
     */
    'id'?: string;
}

