/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClusterConfigurationMode } from './cluster-configuration-mode';
// May contain unused imports in some cases
// @ts-ignore
import { ClusterState } from './cluster-state';

/**
 * Detailed status of a cluster.
 * @export
 * @interface ClusterStatus
 */
export interface ClusterStatus {
    /**
     * Indicates the type of this object. Will be \'ClusterStatus\' if this is a complete object or \'ClusterStatusLink\' if it is just a link.
     * @type {string}
     * @memberof ClusterStatus
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof ClusterStatus
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof ClusterStatus
     */
    'href'?: string;
    /**
     * DNSReady from Provisioner
     * @type {boolean}
     * @memberof ClusterStatus
     */
    'dns_ready'?: boolean;
    /**
     * OIDCReady from user configuration.
     * @type {boolean}
     * @memberof ClusterStatus
     */
    'oidc_ready'?: boolean;
    /**
     * 
     * @type {ClusterConfigurationMode}
     * @memberof ClusterStatus
     */
    'configuration_mode'?: ClusterConfigurationMode;
    /**
     * Current Replicas available for a Hosted Cluster
     * @type {number}
     * @memberof ClusterStatus
     */
    'current_compute'?: number;
    /**
     * Detailed description of the cluster status.
     * @type {string}
     * @memberof ClusterStatus
     */
    'description'?: string;
    /**
     * Limited Support Reason Count
     * @type {number}
     * @memberof ClusterStatus
     */
    'limited_support_reason_count'?: number;
    /**
     * Provisioning Error Code
     * @type {string}
     * @memberof ClusterStatus
     */
    'provision_error_code'?: string;
    /**
     * Provisioning Error Message
     * @type {string}
     * @memberof ClusterStatus
     */
    'provision_error_message'?: string;
    /**
     * 
     * @type {ClusterState}
     * @memberof ClusterStatus
     */
    'state'?: ClusterState;
}



