/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information about the console of a cluster.
 * @export
 * @interface ClusterConsole
 */
export interface ClusterConsole {
    /**
     * The URL of the console of the cluster.
     * @type {string}
     * @memberof ClusterConsole
     */
    'url'?: string;
}

