/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of a clusterdeployment.
 * @export
 * @interface ClusterDeployment
 */
export interface ClusterDeployment {
    /**
     * Indicates the type of this object. Will be \'ClusterDeployment\' if this is a complete object or \'ClusterDeploymentLink\' if it is just a link.
     * @type {string}
     * @memberof ClusterDeployment
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof ClusterDeployment
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof ClusterDeployment
     */
    'href'?: string;
    /**
     * Content of the clusterdeployment.
     * @type {object}
     * @memberof ClusterDeployment
     */
    'content'?: object;
}

