/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ScheduleType } from './schedule-type';
// May contain unused imports in some cases
// @ts-ignore
import { UpgradePolicyState } from './upgrade-policy-state';
// May contain unused imports in some cases
// @ts-ignore
import { UpgradeType } from './upgrade-type';

/**
 * Representation of an upgrade policy that can be set for a cluster.
 * @export
 * @interface ControlPlaneUpgradePolicy
 */
export interface ControlPlaneUpgradePolicy {
    /**
     * Indicates the type of this object. Will be \'ControlPlaneUpgradePolicy\' if this is a complete object or \'ControlPlaneUpgradePolicyLink\' if it is just a link.
     * @type {string}
     * @memberof ControlPlaneUpgradePolicy
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof ControlPlaneUpgradePolicy
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof ControlPlaneUpgradePolicy
     */
    'href'?: string;
    /**
     * Cluster ID this upgrade policy for control plane is defined for.
     * @type {string}
     * @memberof ControlPlaneUpgradePolicy
     */
    'cluster_id'?: string;
    /**
     * Timestamp for creation of resource.
     * @type {string}
     * @memberof ControlPlaneUpgradePolicy
     */
    'creation_timestamp'?: string;
    /**
     * Indicates if minor version upgrades are allowed for automatic upgrades (for manual it\'s always allowed).
     * @type {boolean}
     * @memberof ControlPlaneUpgradePolicy
     */
    'enable_minor_version_upgrades'?: boolean;
    /**
     * Timestamp for last update that happened to resource.
     * @type {string}
     * @memberof ControlPlaneUpgradePolicy
     */
    'last_update_timestamp'?: string;
    /**
     * Next time the upgrade should run.
     * @type {string}
     * @memberof ControlPlaneUpgradePolicy
     */
    'next_run'?: string;
    /**
     * Schedule cron expression that defines automatic upgrade scheduling.
     * @type {string}
     * @memberof ControlPlaneUpgradePolicy
     */
    'schedule'?: string;
    /**
     * 
     * @type {ScheduleType}
     * @memberof ControlPlaneUpgradePolicy
     */
    'schedule_type'?: ScheduleType;
    /**
     * 
     * @type {UpgradePolicyState}
     * @memberof ControlPlaneUpgradePolicy
     */
    'state'?: UpgradePolicyState;
    /**
     * 
     * @type {UpgradeType}
     * @memberof ControlPlaneUpgradePolicy
     */
    'upgrade_type'?: UpgradeType;
    /**
     * Version is the desired upgrade version.
     * @type {string}
     * @memberof ControlPlaneUpgradePolicy
     */
    'version'?: string;
}



