/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DeleteProtection configuration.
 * @export
 * @interface DeleteProtection
 */
export interface DeleteProtection {
    /**
     * Boolean flag indicating if the cluster should be be using _DeleteProtection_.  By default this is `false`.  To enable it a SREP needs to patch the value through OCM API
     * @type {boolean}
     * @memberof DeleteProtection
     */
    'enabled'?: boolean;
}

