/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Description of an environment
 * @export
 * @interface Environment
 */
export interface Environment {
    /**
     * last time that the worker checked for limited support clusters
     * @type {string}
     * @memberof Environment
     */
    'last_limited_support_check'?: string;
    /**
     * last time that the worker checked for available upgrades
     * @type {string}
     * @memberof Environment
     */
    'last_upgrade_available_check'?: string;
    /**
     * environment name
     * @type {string}
     * @memberof Environment
     */
    'name'?: string;
}

