/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Counts of different classes of nodes inside a flavour.
 * @export
 * @interface FlavourNodes
 */
export interface FlavourNodes {
    /**
     * Number of master nodes of the cluster.
     * @type {number}
     * @memberof FlavourNodes
     */
    'master'?: number;
}

