/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Google cloud platform settings of a cluster.
 * @export
 * @interface GCP
 */
export interface GCP {
    /**
     * GCP authentication uri
     * @type {string}
     * @memberof GCP
     */
    'auth_uri'?: string;
    /**
     * GCP Authentication provider x509 certificate url
     * @type {string}
     * @memberof GCP
     */
    'auth_provider_x509_cert_url'?: string;
    /**
     * GCP client identifier
     * @type {string}
     * @memberof GCP
     */
    'client_id'?: string;
    /**
     * GCP client x509 certificate url
     * @type {string}
     * @memberof GCP
     */
    'client_x509_cert_url'?: string;
    /**
     * GCP client email
     * @type {string}
     * @memberof GCP
     */
    'client_email'?: string;
    /**
     * GCP private key
     * @type {string}
     * @memberof GCP
     */
    'private_key'?: string;
    /**
     * GCP private key identifier
     * @type {string}
     * @memberof GCP
     */
    'private_key_id'?: string;
    /**
     * GCP project identifier.
     * @type {string}
     * @memberof GCP
     */
    'project_id'?: string;
    /**
     * GCP token uri
     * @type {string}
     * @memberof GCP
     */
    'token_uri'?: string;
    /**
     * GCP the type of the service the key belongs to
     * @type {string}
     * @memberof GCP
     */
    'type'?: string;
}

