/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GCPVolume } from './gcpvolume';

/**
 * Specification for different classes of nodes inside a flavour.
 * @export
 * @interface GCPFlavour
 */
export interface GCPFlavour {
    /**
     * GCP default instance type for the worker volume.  User can be overridden specifying in the cluster itself a type for compute node.
     * @type {string}
     * @memberof GCPFlavour
     */
    'compute_instance_type'?: string;
    /**
     * GCP default instance type for the infra volume.
     * @type {string}
     * @memberof GCPFlavour
     */
    'infra_instance_type'?: string;
    /**
     * 
     * @type {GCPVolume}
     * @memberof GCPFlavour
     */
    'infra_volume'?: GCPVolume;
    /**
     * GCP default instance type for the master volume.
     * @type {string}
     * @memberof GCPFlavour
     */
    'master_instance_type'?: string;
    /**
     * 
     * @type {GCPVolume}
     * @memberof GCPFlavour
     */
    'master_volume'?: GCPVolume;
    /**
     * 
     * @type {GCPVolume}
     * @memberof GCPFlavour
     */
    'worker_volume'?: GCPVolume;
}

