/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * GCP Network configuration of a cluster.
 * @export
 * @interface GCPNetwork
 */
export interface GCPNetwork {
    /**
     * VPC mame used by the cluster.
     * @type {string}
     * @memberof GCPNetwork
     */
    'vpc_name'?: string;
    /**
     * The name of the host project where the shared VPC exists.
     * @type {string}
     * @memberof GCPNetwork
     */
    'vpc_project_id'?: string;
    /**
     * Compute subnet used by the cluster.
     * @type {string}
     * @memberof GCPNetwork
     */
    'compute_subnet'?: string;
    /**
     * Control plane subnet used by the cluster.
     * @type {string}
     * @memberof GCPNetwork
     */
    'control_plane_subnet'?: string;
}

