/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Details for `gitlab` identity providers.
 * @export
 * @interface GitlabIdentityProvider
 */
export interface GitlabIdentityProvider {
    /**
     * Optional trusted certificate authority bundle to use when making requests tot he server.
     * @type {string}
     * @memberof GitlabIdentityProvider
     */
    'ca'?: string;
    /**
     * URL of the _GitLab_ instance.
     * @type {string}
     * @memberof GitlabIdentityProvider
     */
    'url'?: string;
    /**
     * Client identifier of a registered _GitLab_ OAuth application.
     * @type {string}
     * @memberof GitlabIdentityProvider
     */
    'client_id'?: string;
    /**
     * Client secret issued by _GitLab_.
     * @type {string}
     * @memberof GitlabIdentityProvider
     */
    'client_secret'?: string;
}

