/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * Representation of a group of users.
 * @export
 * @interface Group
 */
export interface Group {
    /**
     * Indicates the type of this object. Will be \'Group\' if this is a complete object or \'GroupLink\' if it is just a link.
     * @type {string}
     * @memberof Group
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof Group
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof Group
     */
    'href'?: string;
    /**
     * List of users of the group.
     * @type {Array<User>}
     * @memberof Group
     */
    'users'?: Array<User>;
}

