/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ListeningMethod } from './listening-method';
// May contain unused imports in some cases
// @ts-ignore
import { LoadBalancerFlavor } from './load-balancer-flavor';
// May contain unused imports in some cases
// @ts-ignore
import { NamespaceOwnershipPolicy } from './namespace-ownership-policy';
// May contain unused imports in some cases
// @ts-ignore
import { WildcardPolicy } from './wildcard-policy';

/**
 * Representation of an ingress.
 * @export
 * @interface Ingress
 */
export interface Ingress {
    /**
     * Indicates the type of this object. Will be \'Ingress\' if this is a complete object or \'IngressLink\' if it is just a link.
     * @type {string}
     * @memberof Ingress
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof Ingress
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof Ingress
     */
    'href'?: string;
    /**
     * DNS Name of the ingress.
     * @type {string}
     * @memberof Ingress
     */
    'dns_name'?: string;
    /**
     * Cluster routes hostname.
     * @type {string}
     * @memberof Ingress
     */
    'cluster_routes_hostname'?: string;
    /**
     * Cluster routes TLS Secret reference.
     * @type {string}
     * @memberof Ingress
     */
    'cluster_routes_tls_secret_ref'?: string;
    /**
     * Indicates if this is the default ingress.
     * @type {boolean}
     * @memberof Ingress
     */
    'default'?: boolean;
    /**
     * A set of excluded namespaces for the ingress.
     * @type {Array<string>}
     * @memberof Ingress
     */
    'excluded_namespaces'?: Array<string>;
    /**
     * 
     * @type {ListeningMethod}
     * @memberof Ingress
     */
    'listening'?: ListeningMethod;
    /**
     * 
     * @type {LoadBalancerFlavor}
     * @memberof Ingress
     */
    'load_balancer_type'?: LoadBalancerFlavor;
    /**
     * 
     * @type {NamespaceOwnershipPolicy}
     * @memberof Ingress
     */
    'route_namespace_ownership_policy'?: NamespaceOwnershipPolicy;
    /**
     * A set of labels for the ingress. 
     * @type {{ [key: string]: string; }}
     * @memberof Ingress
     */
    'route_selectors'?: { [key: string]: string; };
    /**
     * 
     * @type {WildcardPolicy}
     * @memberof Ingress
     */
    'route_wildcard_policy'?: WildcardPolicy;
}



