/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Contains the necessary attributes to support role-based authentication on AWS.
 * @export
 * @interface InstanceIAMRoles
 */
export interface InstanceIAMRoles {
    /**
     * The IAM role ARN that will be attached to master instances
     * @type {string}
     * @memberof InstanceIAMRoles
     */
    'master_role_arn'?: string;
    /**
     * The IAM role ARN that will be attached to worker instances
     * @type {string}
     * @memberof InstanceIAMRoles
     */
    'worker_role_arn'?: string;
}

