/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of a label in clusterdeployment.
 * @export
 * @interface Label
 */
export interface Label {
    /**
     * Indicates the type of this object. Will be \'Label\' if this is a complete object or \'LabelLink\' if it is just a link.
     * @type {string}
     * @memberof Label
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof Label
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof Label
     */
    'href'?: string;
    /**
     * the key of the label
     * @type {string}
     * @memberof Label
     */
    'key'?: string;
    /**
     * the value to set in the label
     * @type {string}
     * @memberof Label
     */
    'value'?: string;
}

