/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DetectionType } from './detection-type';
// May contain unused imports in some cases
// @ts-ignore
import { LimitedSupportReasonTemplate } from './limited-support-reason-template';

/**
 * A reason that a cluster is in limited support.
 * @export
 * @interface LimitedSupportReason
 */
export interface LimitedSupportReason {
    /**
     * Indicates the type of this object. Will be \'LimitedSupportReason\' if this is a complete object or \'LimitedSupportReasonLink\' if it is just a link.
     * @type {string}
     * @memberof LimitedSupportReason
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof LimitedSupportReason
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof LimitedSupportReason
     */
    'href'?: string;
    /**
     * The time the reason was detected.
     * @type {string}
     * @memberof LimitedSupportReason
     */
    'creation_timestamp'?: string;
    /**
     * URL with a link to a detailed description of the reason.
     * @type {string}
     * @memberof LimitedSupportReason
     */
    'details'?: string;
    /**
     * 
     * @type {DetectionType}
     * @memberof LimitedSupportReason
     */
    'detection_type'?: DetectionType;
    /**
     * Summary of the reason.
     * @type {string}
     * @memberof LimitedSupportReason
     */
    'summary'?: string;
    /**
     * 
     * @type {LimitedSupportReasonTemplate}
     * @memberof LimitedSupportReason
     */
    'template'?: LimitedSupportReasonTemplate;
}



