/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Machine type category.
 * @export
 * @enum {string}
 */

export enum MachineTypeCategory {
    AcceleratedComputing = 'accelerated_computing',
    ComputeOptimized = 'compute_optimized',
    GeneralPurpose = 'general_purpose',
    MemoryOptimized = 'memory_optimized'
}



