/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AWSMachinePool } from './awsmachine-pool';
// May contain unused imports in some cases
// @ts-ignore
import { MachinePoolAutoscaling } from './machine-pool-autoscaling';
// May contain unused imports in some cases
// @ts-ignore
import { MachinePoolSecurityGroupFilter } from './machine-pool-security-group-filter';
// May contain unused imports in some cases
// @ts-ignore
import { RootVolume } from './root-volume';
// May contain unused imports in some cases
// @ts-ignore
import { Taint } from './taint';

/**
 * Representation of a machine pool in a cluster.
 * @export
 * @interface MachinePool
 */
export interface MachinePool {
    /**
     * Indicates the type of this object. Will be \'MachinePool\' if this is a complete object or \'MachinePoolLink\' if it is just a link.
     * @type {string}
     * @memberof MachinePool
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof MachinePool
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof MachinePool
     */
    'href'?: string;
    /**
     * 
     * @type {AWSMachinePool}
     * @memberof MachinePool
     */
    'aws'?: AWSMachinePool;
    /**
     * 
     * @type {MachinePoolAutoscaling}
     * @memberof MachinePool
     */
    'autoscaling'?: MachinePoolAutoscaling;
    /**
     * The availability zones upon which the nodes are created.
     * @type {Array<string>}
     * @memberof MachinePool
     */
    'availability_zones'?: Array<string>;
    /**
     * The instance type of Nodes to create.
     * @type {string}
     * @memberof MachinePool
     */
    'instance_type'?: string;
    /**
     * The labels set on the Nodes created.
     * @type {{ [key: string]: string; }}
     * @memberof MachinePool
     */
    'labels'?: { [key: string]: string; };
    /**
     * The number of Machines (and Nodes) to create. Replicas and autoscaling cannot be used together.
     * @type {number}
     * @memberof MachinePool
     */
    'replicas'?: number;
    /**
     * 
     * @type {RootVolume}
     * @memberof MachinePool
     */
    'root_volume'?: RootVolume;
    /**
     * List of security groups to be applied to MachinePool (Optional)
     * @type {Array<MachinePoolSecurityGroupFilter>}
     * @memberof MachinePool
     */
    'security_group_filters'?: Array<MachinePoolSecurityGroupFilter>;
    /**
     * The subnets upon which the nodes are created.
     * @type {Array<string>}
     * @memberof MachinePool
     */
    'subnets'?: Array<string>;
    /**
     * The taints set on the Nodes created.
     * @type {Array<Taint>}
     * @memberof MachinePool
     */
    'taints'?: Array<Taint>;
}

