/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Contains the necessary attributes to support role-based authentication on AWS.
 * @export
 * @interface ManagedService
 */
export interface ManagedService {
    /**
     * Indicates whether the cluster belongs to a managed service This should only be set by the \"Managed Service\" service. clusters with this set can only be modified by the \"Managed Service\" service.
     * @type {boolean}
     * @memberof ManagedService
     */
    'enabled'?: boolean;
}

