/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of a manifestwork.
 * @export
 * @interface Manifest
 */
export interface Manifest {
    /**
     * Indicates the type of this object. Will be \'Manifest\' if this is a complete object or \'ManifestLink\' if it is just a link.
     * @type {string}
     * @memberof Manifest
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof Manifest
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof Manifest
     */
    'href'?: string;
    /**
     * List of k8s objects to deploy on a hosted cluster.
     * @type {Array<object>}
     * @memberof Manifest
     */
    'workloads'?: Array<object>;
}

