/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Version metadata.
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * Version of the server.
     * @type {string}
     * @memberof Metadata
     */
    'server_version'?: string;
}

