/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of Namespace Ownership Policy.
 * @export
 * @enum {string}
 */

export enum NamespaceOwnershipPolicy {
    InterNamespaceAllowed = 'InterNamespaceAllowed',
    Strict = 'Strict'
}



