/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of the status of a node pool.
 * @export
 * @interface NodePoolStatus
 */
export interface NodePoolStatus {
    /**
     * Indicates the type of this object. Will be \'NodePoolStatus\' if this is a complete object or \'NodePoolStatusLink\' if it is just a link.
     * @type {string}
     * @memberof NodePoolStatus
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof NodePoolStatus
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof NodePoolStatus
     */
    'href'?: string;
    /**
     * The current number of replicas for the node pool.
     * @type {number}
     * @memberof NodePoolStatus
     */
    'current_replicas'?: number;
    /**
     * Adds additional information about the NodePool status when the node pool doesn\'t reach the desired replicas.
     * @type {string}
     * @memberof NodePoolStatus
     */
    'message'?: string;
}

