/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AWSNodePool } from './awsnode-pool';
// May contain unused imports in some cases
// @ts-ignore
import { NodePoolAutoscaling } from './node-pool-autoscaling';
// May contain unused imports in some cases
// @ts-ignore
import { NodePoolStatus } from './node-pool-status';
// May contain unused imports in some cases
// @ts-ignore
import { Taint } from './taint';
// May contain unused imports in some cases
// @ts-ignore
import { Version } from './version';

/**
 * Representation of a node pool in a cluster.
 * @export
 * @interface NodePool
 */
export interface NodePool {
    /**
     * Indicates the type of this object. Will be \'NodePool\' if this is a complete object or \'NodePoolLink\' if it is just a link.
     * @type {string}
     * @memberof NodePool
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof NodePool
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof NodePool
     */
    'href'?: string;
    /**
     * 
     * @type {AWSNodePool}
     * @memberof NodePool
     */
    'aws_node_pool'?: AWSNodePool;
    /**
     * Specifies whether health checks should be enabled for machines in the NodePool.
     * @type {boolean}
     * @memberof NodePool
     */
    'auto_repair'?: boolean;
    /**
     * 
     * @type {NodePoolAutoscaling}
     * @memberof NodePool
     */
    'autoscaling'?: NodePoolAutoscaling;
    /**
     * The availability zone upon which the node is created.
     * @type {string}
     * @memberof NodePool
     */
    'availability_zone'?: string;
    /**
     * The labels set on the Nodes created.
     * @type {{ [key: string]: string; }}
     * @memberof NodePool
     */
    'labels'?: { [key: string]: string; };
    /**
     * The number of Machines (and Nodes) to create. Replicas and autoscaling cannot be used together.
     * @type {number}
     * @memberof NodePool
     */
    'replicas'?: number;
    /**
     * 
     * @type {NodePoolStatus}
     * @memberof NodePool
     */
    'status'?: NodePoolStatus;
    /**
     * The subnet upon which the nodes are created.
     * @type {string}
     * @memberof NodePool
     */
    'subnet'?: string;
    /**
     * The taints set on the Nodes created.
     * @type {Array<Taint>}
     * @memberof NodePool
     */
    'taints'?: Array<Taint>;
    /**
     * The names of the tuning configs for this node pool.
     * @type {Array<string>}
     * @memberof NodePool
     */
    'tuning_configs'?: Array<string>;
    /**
     * 
     * @type {Version}
     * @memberof NodePool
     */
    'version'?: Version;
}

