/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OpenIDClaims } from './open-idclaims';

/**
 * Details for `openid` identity providers.
 * @export
 * @interface OpenIDIdentityProvider
 */
export interface OpenIDIdentityProvider {
    /**
     * Certificate bunde to use to validate server certificates for the configured URL.
     * @type {string}
     * @memberof OpenIDIdentityProvider
     */
    'ca'?: string;
    /**
     * 
     * @type {OpenIDClaims}
     * @memberof OpenIDIdentityProvider
     */
    'claims'?: OpenIDClaims;
    /**
     * Identifier of a client registered with the _OpenID_ provider.
     * @type {string}
     * @memberof OpenIDIdentityProvider
     */
    'client_id'?: string;
    /**
     * Client secret.
     * @type {string}
     * @memberof OpenIDIdentityProvider
     */
    'client_secret'?: string;
    /**
     * Optional map of extra parameters to add to the authorization token request.
     * @type {{ [key: string]: string; }}
     * @memberof OpenIDIdentityProvider
     */
    'extra_authorize_parameters'?: { [key: string]: string; };
    /**
     * Optional list of scopes to request, in addition to the `openid` scope, during the authorization token request.
     * @type {Array<string>}
     * @memberof OpenIDIdentityProvider
     */
    'extra_scopes'?: Array<string>;
    /**
     * The URL that the OpenID Provider asserts as the Issuer Identifier
     * @type {string}
     * @memberof OpenIDIdentityProvider
     */
    'issuer'?: string;
}

