/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Contains the necessary attributes to allow each operator to access the necessary AWS resources
 * @export
 * @interface OperatorIAMRole
 */
export interface OperatorIAMRole {
    /**
     * Randomly-generated ID to identify the operator role
     * @type {string}
     * @memberof OperatorIAMRole
     */
    'id'?: string;
    /**
     * Name of the credentials secret used to access cloud resources
     * @type {string}
     * @memberof OperatorIAMRole
     */
    'name'?: string;
    /**
     * Namespace where the credentials secret lives in the cluster
     * @type {string}
     * @memberof OperatorIAMRole
     */
    'namespace'?: string;
    /**
     * Role to assume when accessing AWS resources
     * @type {string}
     * @memberof OperatorIAMRole
     */
    'role_arn'?: string;
    /**
     * Service account name to use when authenticating
     * @type {string}
     * @memberof OperatorIAMRole
     */
    'service_account'?: string;
}

