/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Definition of an organization link.
 * @export
 * @interface OrganizationLink
 */
export interface OrganizationLink {
    /**
     * HREF for the Organization, filled in response.
     * @type {string}
     * @memberof OrganizationLink
     */
    'href'?: string;
    /**
     * The organization\'s ID.
     * @type {string}
     * @memberof OrganizationLink
     */
    'id'?: string;
}

