/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Cluster } from './cluster';

/**
 * Represents a pending delete entry for a specific cluster.
 * @export
 * @interface PendingDeleteCluster
 */
export interface PendingDeleteCluster {
    /**
     * Indicates the type of this object. Will be \'PendingDeleteCluster\' if this is a complete object or \'PendingDeleteClusterLink\' if it is just a link.
     * @type {string}
     * @memberof PendingDeleteCluster
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof PendingDeleteCluster
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof PendingDeleteCluster
     */
    'href'?: string;
    /**
     * Flag indicating if the cluster deletion should be best-effort mode or not.
     * @type {boolean}
     * @memberof PendingDeleteCluster
     */
    'best_effort'?: boolean;
    /**
     * 
     * @type {Cluster}
     * @memberof PendingDeleteCluster
     */
    'cluster'?: Cluster;
    /**
     * Date and time when the cluster was initially created, using the format defined in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt).
     * @type {string}
     * @memberof PendingDeleteCluster
     */
    'creation_timestamp'?: string;
}

