/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PrivateLinkPrincipals } from './private-link-principals';

/**
 * Manages the configuration for the Private Links.
 * @export
 * @interface PrivateLinkConfiguration
 */
export interface PrivateLinkConfiguration {
    /**
     * 
     * @type {PrivateLinkPrincipals}
     * @memberof PrivateLinkConfiguration
     */
    'principals'?: PrivateLinkPrincipals;
}

