/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PrivateLinkPrincipal } from './private-link-principal';

/**
 * Manages the configuration for the Private Links.
 * @export
 * @interface PrivateLinkClusterConfiguration
 */
export interface PrivateLinkClusterConfiguration {
    /**
     * List of additional principals for the Private Link
     * @type {Array<PrivateLinkPrincipal>}
     * @memberof PrivateLinkClusterConfiguration
     */
    'principals'?: Array<PrivateLinkPrincipal>;
}

