/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PrivateLinkPrincipal } from './private-link-principal';

/**
 * Contains a list of principals for the Private Link.
 * @export
 * @interface PrivateLinkPrincipals
 */
export interface PrivateLinkPrincipals {
    /**
     * Indicates the type of this object. Will be \'PrivateLinkPrincipals\' if this is a complete object or \'PrivateLinkPrincipalsLink\' if it is just a link.
     * @type {string}
     * @memberof PrivateLinkPrincipals
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof PrivateLinkPrincipals
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof PrivateLinkPrincipals
     */
    'href'?: string;
    /**
     * List of additional principals for the Private Link
     * @type {Array<PrivateLinkPrincipal>}
     * @memberof PrivateLinkPrincipals
     */
    'principals'?: Array<PrivateLinkPrincipal>;
}

