/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PrivateLinkPrincipal
 */
export interface PrivateLinkPrincipal {
    /**
     * Indicates the type of this object. Will be \'PrivateLinkPrincipal\' if this is a complete object or \'PrivateLinkPrincipalLink\' if it is just a link.
     * @type {string}
     * @memberof PrivateLinkPrincipal
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof PrivateLinkPrincipal
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof PrivateLinkPrincipal
     */
    'href'?: string;
    /**
     * ARN for a principal that is allowed for this Private Link.
     * @type {string}
     * @memberof PrivateLinkPrincipal
     */
    'principal'?: string;
}

