/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of an product that can be selected as a cluster type.
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * Indicates the type of this object. Will be \'Product\' if this is a complete object or \'ProductLink\' if it is just a link.
     * @type {string}
     * @memberof Product
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof Product
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof Product
     */
    'href'?: string;
    /**
     * Name of the product.
     * @type {string}
     * @memberof Product
     */
    'name'?: string;
}

