/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Proxy configuration of a cluster.
 * @export
 * @interface Proxy
 */
export interface Proxy {
    /**
     * HTTPProxy is the URL of the proxy for HTTP requests.
     * @type {string}
     * @memberof Proxy
     */
    'http_proxy'?: string;
    /**
     * HTTPSProxy is the URL of the proxy for HTTPS requests.
     * @type {string}
     * @memberof Proxy
     */
    'https_proxy'?: string;
    /**
     * NoProxy is a comma-separated list of domains and CIDRs for which  the proxy should not be used
     * @type {string}
     * @memberof Proxy
     */
    'no_proxy'?: string;
}

