/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { InstanceIAMRoles } from './instance-iamroles';
// May contain unused imports in some cases
// @ts-ignore
import { OidcConfig } from './oidc-config';
// May contain unused imports in some cases
// @ts-ignore
import { OperatorIAMRole } from './operator-iamrole';

/**
 * Contains the necessary attributes to support role-based authentication on AWS.
 * @export
 * @interface STS
 */
export interface STS {
    /**
     * URL of the location where OIDC configuration and keys are available
     * @type {string}
     * @memberof STS
     */
    'oidc_endpoint_url'?: string;
    /**
     * Auto creation mode for cluster - OCM will create the operator roles and OIDC provider. false by default.
     * @type {boolean}
     * @memberof STS
     */
    'auto_mode'?: boolean;
    /**
     * If STS is enabled or disabled
     * @type {boolean}
     * @memberof STS
     */
    'enabled'?: boolean;
    /**
     * Optional unique identifier when assuming role in another account
     * @type {string}
     * @memberof STS
     */
    'external_id'?: string;
    /**
     * 
     * @type {InstanceIAMRoles}
     * @memberof STS
     */
    'instance_iam_roles'?: InstanceIAMRoles;
    /**
     * If true, cluster account and operator roles have managed policies attached.
     * @type {boolean}
     * @memberof STS
     */
    'managed_policies'?: boolean;
    /**
     * 
     * @type {OidcConfig}
     * @memberof STS
     */
    'oidc_config'?: OidcConfig;
    /**
     * List of roles necessary to access the AWS resources of the various operators used during installation
     * @type {Array<OperatorIAMRole>}
     * @memberof STS
     */
    'operator_iam_roles'?: Array<OperatorIAMRole>;
    /**
     * Optional user provided prefix for operator roles.
     * @type {string}
     * @memberof STS
     */
    'operator_role_prefix'?: string;
    /**
     * Optional user provided permission boundary.
     * @type {string}
     * @memberof STS
     */
    'permission_boundary'?: string;
    /**
     * ARN of the AWS role to assume when installing the cluster
     * @type {string}
     * @memberof STS
     */
    'role_arn'?: string;
    /**
     * ARN of the AWS role used by SREs to access the cluster AWS account in order to provide support
     * @type {string}
     * @memberof STS
     */
    'support_role_arn'?: string;
}

