/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * AWS subnetwork object to be used while installing a cluster
 * @export
 * @interface Subnetwork
 */
export interface Subnetwork {
    /**
     * The CIDR Block of the subnet.
     * @type {string}
     * @memberof Subnetwork
     */
    'cidr_block'?: string;
    /**
     * The availability zone to which the subnet is related.
     * @type {string}
     * @memberof Subnetwork
     */
    'availability_zone'?: string;
    /**
     * Name of the subnet according to its `Name` tag on AWS.
     * @type {string}
     * @memberof Subnetwork
     */
    'name'?: string;
    /**
     * Whether or not it is a public subnet.
     * @type {boolean}
     * @memberof Subnetwork
     */
    'public'?: boolean;
    /**
     * The subnet ID to be used while installing a cluster.
     * @type {string}
     * @memberof Subnetwork
     */
    'subnet_id'?: string;
}

