/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of a trusted ip address in clusterdeployment.
 * @export
 * @interface TrustedIp
 */
export interface TrustedIp {
    /**
     * Indicates the type of this object. Will be \'TrustedIp\' if this is a complete object or \'TrustedIpLink\' if it is just a link.
     * @type {string}
     * @memberof TrustedIp
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof TrustedIp
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof TrustedIp
     */
    'href'?: string;
    /**
     * The boolean set to show if the ip is enabled.
     * @type {boolean}
     * @memberof TrustedIp
     */
    'enabled'?: boolean;
}

