/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of a tuning config.
 * @export
 * @interface TuningConfig
 */
export interface TuningConfig {
    /**
     * Indicates the type of this object. Will be \'TuningConfig\' if this is a complete object or \'TuningConfigLink\' if it is just a link.
     * @type {string}
     * @memberof TuningConfig
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof TuningConfig
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof TuningConfig
     */
    'href'?: string;
    /**
     * Name of the tuning config.
     * @type {string}
     * @memberof TuningConfig
     */
    'name'?: string;
    /**
     * Spec of the tuning config.
     * @type {object}
     * @memberof TuningConfig
     */
    'spec'?: object;
}

