/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UpgradePolicyStateValue } from './upgrade-policy-state-value';

/**
 * Representation of an upgrade policy state that that is set for a cluster.
 * @export
 * @interface UpgradePolicyState
 */
export interface UpgradePolicyState {
    /**
     * Indicates the type of this object. Will be \'UpgradePolicyState\' if this is a complete object or \'UpgradePolicyStateLink\' if it is just a link.
     * @type {string}
     * @memberof UpgradePolicyState
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof UpgradePolicyState
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof UpgradePolicyState
     */
    'href'?: string;
    /**
     * Description of the state.
     * @type {string}
     * @memberof UpgradePolicyState
     */
    'description'?: string;
    /**
     * 
     * @type {UpgradePolicyStateValue}
     * @memberof UpgradePolicyState
     */
    'value'?: UpgradePolicyStateValue;
}



