/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * UpgradeType defines which type of upgrade should be used.
 * @export
 * @enum {string}
 */

export enum UpgradeType {
    Osd = 'OSD',
    Addon = 'ADDON',
    ControlPlane = 'ControlPlane',
    NodePool = 'NodePool'
}



