/* tslint:disable */
/* eslint-disable */
/**
 * clusters_mgmt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: ocm-feedback@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of an _OpenShift_ version gate.
 * @export
 * @interface VersionGate
 */
export interface VersionGate {
    /**
     * Indicates the type of this object. Will be \'VersionGate\' if this is a complete object or \'VersionGateLink\' if it is just a link.
     * @type {string}
     * @memberof VersionGate
     */
    'kind'?: string;
    /**
     * Unique identifier of the object.
     * @type {string}
     * @memberof VersionGate
     */
    'id'?: string;
    /**
     * Self link.
     * @type {string}
     * @memberof VersionGate
     */
    'href'?: string;
    /**
     * STSOnly indicates if this version gate is for STS clusters only
     * @type {boolean}
     * @memberof VersionGate
     */
    'sts_only'?: boolean;
    /**
     * CreationTimestamp is the date and time when the version gate was created, format defined in https://www.ietf.org/rfc/rfc3339.txt[RC3339].
     * @type {string}
     * @memberof VersionGate
     */
    'creation_timestamp'?: string;
    /**
     * Description of the version gate.
     * @type {string}
     * @memberof VersionGate
     */
    'description'?: string;
    /**
     * DocumentationURL is the URL for the documentation of the version gate.
     * @type {string}
     * @memberof VersionGate
     */
    'documentation_url'?: string;
    /**
     * Label representing the version gate in OpenShift.
     * @type {string}
     * @memberof VersionGate
     */
    'label'?: string;
    /**
     * Value represents the required value of the label.
     * @type {string}
     * @memberof VersionGate
     */
    'value'?: string;
    /**
     * VersionRawIDPrefix represents the versions prefix that the gate applies to.
     * @type {string}
     * @memberof VersionGate
     */
    'version_raw_id_prefix'?: string;
    /**
     * WarningMessage is a warning that will be displayed to the user before they acknowledge the gate
     * @type {string}
     * @memberof VersionGate
     */
    'warning_message'?: string;
}

