/* tslint:disable */
/* eslint-disable */
/**
 * Authorization Service API
 * Enables access control on resources of OCM services
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FeatureReview
 */
export interface FeatureReview {
  /**
   *
   * @type {string}
   * @memberof FeatureReview
   */
  feature: string;
  /**
   *
   * @type {string}
   * @memberof FeatureReview
   */
  account_username?: string;
  /**
   *
   * @type {string}
   * @memberof FeatureReview
   */
  organization_id?: string;
}
