/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiVipConnectivityRequest
 */
export interface ApiVipConnectivityRequest {
  /**
   * URL address of the API.
   * @type {string}
   * @memberof ApiVipConnectivityRequest
   */
  url: string;
  /**
   * A CA certficate to be used when contacting the URL via https.
   * @type {string}
   * @memberof ApiVipConnectivityRequest
   */
  ca_certificate?: string | null;
  /**
   * A string which will be used as Authorization Bearer token to fetch the ignition from ignition_endpoint_url.
   * @type {string}
   * @memberof ApiVipConnectivityRequest
   */
  ignition_endpoint_token?: string | null;
  /**
   * Whether to verify if the API VIP belongs to one of the interfaces (DEPRECATED).
   * @type {boolean}
   * @memberof ApiVipConnectivityRequest
   */
  verify_cidr?: boolean;
}
