/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ClusterHostRequirementsDetails } from './cluster-host-requirements-details';
// May contain unused imports in some cases
// @ts-ignore
import { OperatorHostRequirements } from './operator-host-requirements';

/**
 *
 * @export
 * @interface ClusterHostRequirements
 */
export interface ClusterHostRequirements {
  /**
   * Unique identifier of the host the requirements relate to.
   * @type {string}
   * @memberof ClusterHostRequirements
   */
  host_id?: string;
  /**
   *
   * @type {ClusterHostRequirementsDetails}
   * @memberof ClusterHostRequirements
   */
  ocp?: ClusterHostRequirementsDetails;
  /**
   * Host requirements related to requested operators
   * @type {Array<OperatorHostRequirements>}
   * @memberof ClusterHostRequirements
   */
  operators?: Array<OperatorHostRequirements>;
  /**
   *
   * @type {ClusterHostRequirementsDetails}
   * @memberof ClusterHostRequirements
   */
  total?: ClusterHostRequirementsDetails;
}
