/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ContainerImageAvailability } from './container-image-availability';

/**
 *
 * @export
 * @interface ContainerImageAvailabilityResponse
 */
export interface ContainerImageAvailabilityResponse {
  /**
   * List of images that were checked.
   * @type {Array<ContainerImageAvailability>}
   * @memberof ContainerImageAvailabilityResponse
   */
  images: Array<ContainerImageAvailability>;
}
