/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DomainResolutionRequestDomainsInner
 */
export interface DomainResolutionRequestDomainsInner {
  /**
   * The domain name that should be resolved
   * @type {string}
   * @memberof DomainResolutionRequestDomainsInner
   */
  domain_name: string;
}
