/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { FeatureSupportLevel } from './feature-support-level';

/**
 * (DEPRECATED) List of objects that containing a list of feature-support level and attached to openshift-version
 * @export
 * @interface FeatureSupportLevels
 */
export interface FeatureSupportLevels extends Array<FeatureSupportLevel> {}
