/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { FeatureSupportLevelFeaturesInner } from './feature-support-level-features-inner';

/**
 * (DEPRECATED) List of features attached to openshift version
 * @export
 * @interface FeatureSupportLevel
 */
export interface FeatureSupportLevel {
  /**
   *
   * @type {Array<FeatureSupportLevelFeaturesInner>}
   * @memberof FeatureSupportLevel
   */
  features?: Array<FeatureSupportLevelFeaturesInner>;
  /**
   * Version of the OpenShift cluster.
   * @type {string}
   * @memberof FeatureSupportLevel
   */
  openshift_version?: string;
}
