/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */

export enum HostStage {
  StartingInstallation = 'Starting installation',
  WaitingForControlPlane = 'Waiting for control plane',
  WaitingForBootkube = 'Waiting for bootkube',
  WaitingForController = 'Waiting for controller',
  Installing = 'Installing',
  WritingImageToDisk = 'Writing image to disk',
  Rebooting = 'Rebooting',
  WaitingForIgnition = 'Waiting for ignition',
  Configuring = 'Configuring',
  Joined = 'Joined',
  Done = 'Done',
  Failed = 'Failed',
}
