/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { HostStaticNetworkConfig } from './host-static-network-config';
// May contain unused imports in some cases
// @ts-ignore
import { ImageType } from './image-type';
// May contain unused imports in some cases
// @ts-ignore
import { KernelArguments } from './kernel-arguments';
// May contain unused imports in some cases
// @ts-ignore
import { Proxy } from './proxy';

/**
 *
 * @export
 * @interface InfraEnvUpdateParams
 */
export interface InfraEnvUpdateParams {
  /**
   * A comma-separated list of NTP sources (name or IP) going to be added to all the hosts.
   * @type {string}
   * @memberof InfraEnvUpdateParams
   */
  additional_ntp_sources?: string | null;
  /**
   * Allows users to change the additional_trust_bundle infra-env field
   * @type {string}
   * @memberof InfraEnvUpdateParams
   */
  additional_trust_bundle?: string | null;
  /**
   * JSON formatted string containing the user overrides for the initial ignition config.
   * @type {string}
   * @memberof InfraEnvUpdateParams
   */
  ignition_config_override?: string;
  /**
   *
   * @type {ImageType}
   * @memberof InfraEnvUpdateParams
   */
  image_type?: ImageType;
  /**
   *
   * @type {KernelArguments}
   * @memberof InfraEnvUpdateParams
   */
  kernel_arguments?: KernelArguments;
  /**
   *
   * @type {Proxy}
   * @memberof InfraEnvUpdateParams
   */
  proxy?: Proxy;
  /**
   * The pull secret obtained from Red Hat OpenShift Cluster Manager at console.redhat.com/openshift/install/pull-secret.
   * @type {string}
   * @memberof InfraEnvUpdateParams
   */
  pull_secret?: string;
  /**
   * SSH public key for debugging the installation.
   * @type {string}
   * @memberof InfraEnvUpdateParams
   */
  ssh_authorized_key?: string | null;
  /**
   *
   * @type {Array<HostStaticNetworkConfig>}
   * @memberof InfraEnvUpdateParams
   */
  static_network_config?: Array<HostStaticNetworkConfig>;
}
