/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface L2Connectivity
 */
export interface L2Connectivity {
  /**
   *
   * @type {string}
   * @memberof L2Connectivity
   */
  outgoing_ip_address?: string;
  /**
   *
   * @type {string}
   * @memberof L2Connectivity
   */
  outgoing_nic?: string;
  /**
   *
   * @type {string}
   * @memberof L2Connectivity
   */
  remote_ip_address?: string;
  /**
   *
   * @type {string}
   * @memberof L2Connectivity
   */
  remote_mac?: string;
  /**
   *
   * @type {boolean}
   * @memberof L2Connectivity
   */
  successful?: boolean;
}
