/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface L3Connectivity
 */
export interface L3Connectivity {
  /**
   * Average round trip time in milliseconds.
   * @type {number}
   * @memberof L3Connectivity
   */
  average_rtt_ms?: number;
  /**
   *
   * @type {string}
   * @memberof L3Connectivity
   */
  outgoing_nic?: string;
  /**
   * Percentage of packets lost during connectivity check.
   * @type {number}
   * @memberof L3Connectivity
   */
  packet_loss_percentage?: number;
  /**
   *
   * @type {string}
   * @memberof L3Connectivity
   */
  remote_ip_address?: string;
  /**
   *
   * @type {boolean}
   * @memberof L3Connectivity
   */
  successful?: boolean;
}
