/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OperatorCreateParams
 */
export interface OperatorCreateParams {
  /**
   *
   * @type {string}
   * @memberof OperatorCreateParams
   */
  name?: string;
  /**
   * Blob of operator-dependent parameters that are required for installation.
   * @type {string}
   * @memberof OperatorCreateParams
   */
  properties?: string;
}
