/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the operator state.
 * @export
 * @enum {string}
 */

export enum OperatorStatus {
  Failed = 'failed',
  Progressing = 'progressing',
  Available = 'available',
}
