/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { HostTypeHardwareRequirementsWrapper } from './host-type-hardware-requirements-wrapper';

/**
 *
 * @export
 * @interface OperatorHardwareRequirements
 */
export interface OperatorHardwareRequirements {
  /**
   * List of other operator unique names that are required to be installed. Corresponds to name property of the monitored-operator, i.e. \"lso\", \"cnv\", etc.
   * @type {Array<string>}
   * @memberof OperatorHardwareRequirements
   */
  dependencies?: Array<string>;
  /**
   * Unique name of the operator. Corresponds to name property of the monitored-operator, i.e. \"lso\", \"cnv\", etc.
   * @type {string}
   * @memberof OperatorHardwareRequirements
   */
  operator_name?: string;
  /**
   *
   * @type {HostTypeHardwareRequirementsWrapper}
   * @memberof OperatorHardwareRequirements
   */
  requirements?: HostTypeHardwareRequirementsWrapper;
}
