/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { HostTypeHardwareRequirementsWrapper } from './host-type-hardware-requirements-wrapper';
// May contain unused imports in some cases
// @ts-ignore
import { OperatorHardwareRequirements } from './operator-hardware-requirements';

/**
 *
 * @export
 * @interface PreflightHardwareRequirements
 */
export interface PreflightHardwareRequirements {
  /**
   *
   * @type {HostTypeHardwareRequirementsWrapper}
   * @memberof PreflightHardwareRequirements
   */
  ocp?: HostTypeHardwareRequirementsWrapper;
  /**
   * Preflight operators hardware requirements
   * @type {Array<OperatorHardwareRequirements>}
   * @memberof PreflightHardwareRequirements
   */
  operators?: Array<OperatorHardwareRequirements>;
}
