/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { VipType } from './vip-type';
// May contain unused imports in some cases
// @ts-ignore
import { VipVerification } from './vip-verification';

/**
 * Single VIP verification result.
 * @export
 * @interface VerifiedVip
 */
export interface VerifiedVip {
  /**
   *
   * @type {VipVerification}
   * @memberof VerifiedVip
   */
  verification?: VipVerification;
  /**
   *
   * @type {string}
   * @memberof VerifiedVip
   */
  vip?: string;
  /**
   *
   * @type {VipType}
   * @memberof VerifiedVip
   */
  vip_type?: VipType;
}
