/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { VipType } from './vip-type';

/**
 * Request to verify single vip.
 * @export
 * @interface VerifyVip
 */
export interface VerifyVip {
  /**
   *
   * @type {string}
   * @memberof VerifyVip
   */
  vip?: string;
  /**
   *
   * @type {VipType}
   * @memberof VerifyVip
   */
  vip_type?: VipType;
}
