package_manager: yarn
base_branch: master

validation:
  build: yarn workspace @openshift-assisted/ui-lib build
  lint: yarn lint:all
  format: yarn format:all
  test: yarn test:unit
  # audit is only executed by the ai-cve-bot flow
  audit: yarn audit --level high
