/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ApiVipConnectivityAdditionalRequestHeader {
  /**
   * Value of the header\'s key when making a request
   */
  key?: string;
  /**
   * The value corresponding to the header key
   */
  value?: string;
}
