/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The response from the day-2 agent\'s attempt to download the worker ignition file from the API machine config server of the target cluster. Note - the name \"API VIP connectivity\" is old and misleading and is preserved for backwards compatibility.
 * @export
 * @interface ApiVipConnectivityResponse
 */
export interface ApiVipConnectivityResponse {
  /**
   * The error that occurred while downloading the worker ignition file, ignored when is_success is true
   * @type {string}
   * @memberof ApiVipConnectivityResponse
   */
  download_error?: string;
  /**
   * Ignition file fetched from the target cluster\'s API machine config server. This ignition file may be incomplete as almost all files / systemd units are removed from it by the agent in order to save space.
   * @type {string}
   * @memberof ApiVipConnectivityResponse
   */
  ignition?: string;
  /**
   * Whether the agent was able to download the ignition or not
   * @type {boolean}
   * @memberof ApiVipConnectivityResponse
   */
  is_success?: boolean;
  /**
   * This parameter mirrors the url parameter of the corresponding api_vip_connectivity_request
   * @type {string}
   * @memberof ApiVipConnectivityResponse
   */
  url?: string;
}
