/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ApiVipConnectivityAdditionalRequestHeader } from './api-vip-connectivity-additional-request-header';

export interface ApiVipConnectivityRequest {
  /**
   * URL address of the API.
   */
  url: string;
  /**
   * A CA certficate to be used when contacting the URL via https.
   */
  ca_certificate?: string | null;
  /**
   * A string which will be used as Authorization Bearer token to fetch the ignition from ignition_endpoint_url (DEPRECATED use request_headers to pass this token).
   */
  ignition_endpoint_token?: string | null;
  /**
   * Additional request headers to include when fetching the ignition from ignition_endpoint_url.
   */
  request_headers?: Array<ApiVipConnectivityAdditionalRequestHeader> | null;
  /**
   * Whether to verify if the API VIP belongs to one of the interfaces (DEPRECATED).
   */
  verify_cidr?: boolean;
}
