/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SecureBootState } from './secure-boot-state';

export interface Boot {
  command_line?: string;
  current_boot_mode?: string;
  device_type?: BootDeviceTypeEnum;
  pxe_interface?: string;
  secure_boot_state?: SecureBootState;
}

export enum BootDeviceTypeEnum {
  Persistent = 'persistent',
  Ephemeral = 'ephemeral',
}
