/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Bundle {
  /**
   * Longer human friendly description for the bundle, usually one or more sentences.
   */
  description?: string;
  /**
   * Unique identifier of the bundle, for example `virtualization` or `openshift-ai-nvidia`.
   */
  id?: string;
  /**
   * List of operators always included in the bundle.
   */
  operators?: Array<string>;
  /**
   * List of operators that can be optionally selected by the user for this bundle. All are selected by default.
   */
  optional_operators?: Array<string>;
  /**
   * Short human friendly description for the bundle, usually only a few words, for example `Virtualization` or `OpenShift AI (NVIDIA)`.
   */
  title?: string;
}
