/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */

export enum ClusterValidationId {
  MachineCidrDefined = 'machine-cidr-defined',
  ClusterCidrDefined = 'cluster-cidr-defined',
  ServiceCidrDefined = 'service-cidr-defined',
  NoCidrsOverlapping = 'no-cidrs-overlapping',
  NetworksSameAddressFamilies = 'networks-same-address-families',
  NetworkPrefixValid = 'network-prefix-valid',
  MachineCidrEqualsToCalculatedCidr = 'machine-cidr-equals-to-calculated-cidr',
  ApiVipsDefined = 'api-vips-defined',
  ApiVipsValid = 'api-vips-valid',
  IngressVipsDefined = 'ingress-vips-defined',
  IngressVipsValid = 'ingress-vips-valid',
  AllHostsAreReadyToInstall = 'all-hosts-are-ready-to-install',
  SufficientMastersCount = 'sufficient-masters-count',
  DnsDomainDefined = 'dns-domain-defined',
  PullSecretSet = 'pull-secret-set',
  NtpServerConfigured = 'ntp-server-configured',
  LsoRequirementsSatisfied = 'lso-requirements-satisfied',
  OcsRequirementsSatisfied = 'ocs-requirements-satisfied',
  OdfRequirementsSatisfied = 'odf-requirements-satisfied',
  CnvRequirementsSatisfied = 'cnv-requirements-satisfied',
  LvmRequirementsSatisfied = 'lvm-requirements-satisfied',
  MceRequirementsSatisfied = 'mce-requirements-satisfied',
  NetworkTypeValid = 'network-type-valid',
  PlatformRequirementsSatisfied = 'platform-requirements-satisfied',
}
