/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ApiVip } from './api-vip';
// May contain unused imports in some cases
// @ts-ignore
import type { BundleCreateParams } from './bundle-create-params';
// May contain unused imports in some cases
// @ts-ignore
import type { ClusterNetwork } from './cluster-network';
// May contain unused imports in some cases
// @ts-ignore
import type { ClusterProgressInfo } from './cluster-progress-info';
// May contain unused imports in some cases
// @ts-ignore
import type { DiskEncryption } from './disk-encryption';
// May contain unused imports in some cases
// @ts-ignore
import type { Host } from './host';
// May contain unused imports in some cases
// @ts-ignore
import type { HostNetwork } from './host-network';
// May contain unused imports in some cases
// @ts-ignore
import type { IgnitionEndpoint } from './ignition-endpoint';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageInfo } from './image-info';
// May contain unused imports in some cases
// @ts-ignore
import type { IngressVip } from './ingress-vip';
// May contain unused imports in some cases
// @ts-ignore
import type { LastInstallationPreparation } from './last-installation-preparation';
// May contain unused imports in some cases
// @ts-ignore
import type { LoadBalancer } from './load-balancer';
// May contain unused imports in some cases
// @ts-ignore
import type { LogsState } from './logs-state';
// May contain unused imports in some cases
// @ts-ignore
import type { MachineNetwork } from './machine-network';
// May contain unused imports in some cases
// @ts-ignore
import type { MonitoredOperator } from './monitored-operator';
// May contain unused imports in some cases
// @ts-ignore
import type { Platform } from './platform';
// May contain unused imports in some cases
// @ts-ignore
import type { ServiceNetwork } from './service-network';

export interface Cluster {
  /**
   * Self link.
   */
  href: string;
  /**
   * Unique identifier of the object.
   */
  id: string;
  image_info: ImageInfo;
  /**
   * Indicates the type of this object. Will be \'Cluster\' if this is a complete object, \'AddHostsCluster\' for cluster that add hosts to existing OCP cluster, \'DisconnectedCluster\' for clusters with embedded ignition for offline installation,
   */
  kind: ClusterKindEnum;
  /**
   * Status of the OpenShift cluster.
   */
  status: ClusterStatusEnum;
  /**
   * Additional information pertaining to the status of the OpenShift cluster.
   */
  status_info: string;
  /**
   * A comma-separated list of NTP sources (name or IP) going to be added to all the hosts.
   */
  additional_ntp_source?: string;
  /**
   * Unique identifier of the AMS subscription in OCM.
   */
  ams_subscription_id?: string;
  /**
   * The domain name used to reach the OpenShift cluster API.
   */
  api_vip_dns_name?: string | null;
  /**
   * The virtual IPs used to reach the OpenShift cluster\'s API. Enter one IP address for single-stack clusters, or up to two for dual-stack clusters (at most one IP address per IP stack used). The order of stacks should be the same as order of subnets in Cluster Networks, Service Networks, and Machine Networks.
   */
  api_vips?: Array<ApiVip> | null;
  /**
   * Base domain of the cluster. All DNS records must be sub-domains of this base and include the cluster name.
   */
  base_dns_domain?: string;
  /**
   * IP address block from which Pod IPs are allocated. This block must not overlap with existing physical networks. These IP addresses are used for the Pod network, and if you need to access the Pods from an external network, configure load balancers and routers to manage the traffic.
   */
  cluster_network_cidr?: string;
  /**
   * The subnet prefix length to assign to each individual node. For example, if clusterNetworkHostPrefix is set to 23, then each node is assigned a /23 subnet out of the given cidr (clusterNetworkCIDR), which allows for 510 (2^(32 - 23) - 2) pod IPs addresses. If you are required to provide access to nodes from an external network, configure load balancers and routers to manage the traffic.
   */
  cluster_network_host_prefix?: number;
  /**
   * Cluster networks that are associated with this cluster.
   */
  cluster_networks?: Array<ClusterNetwork> | null;
  /**
   * Json formatted string containing the majority groups for connectivity checks.
   */
  connectivity_majority_groups?: string;
  /**
   * Specifies the required number of control plane nodes that should be part of the cluster.
   */
  control_plane_count?: number;
  controller_logs_collected_at?: string;
  controller_logs_started_at?: string;
  /**
   * The CPU architecture of the image (x86_64/arm64/etc).
   */
  cpu_architecture?: ClusterCpuArchitectureEnum;
  /**
   * The time that this cluster was created.
   */
  created_at?: string;
  /**
   * swagger:ignore
   */
  deleted_at?: object;
  disk_encryption?: DiskEncryption;
  email_domain?: string;
  /**
   * hosts associated to this cluster that are not in \'disabled\' state.
   */
  enabled_host_count?: number;
  /**
   * JSON-formatted string containing the usage information by feature name
   */
  feature_usage?: string;
  /**
   * (DEPRECATED) Please use \'control_plane_count\' instead. Guaranteed availability of the installed cluster. \'Full\' installs a Highly-Available cluster over multiple master nodes whereas \'None\' installs a full cluster over one node.
   */
  high_availability_mode?: ClusterHighAvailabilityModeEnum;
  /**
   * List of host networks to be filled during query.
   */
  host_networks?: Array<HostNetwork> | null;
  /**
   * Hosts that are associated with this cluster.
   */
  hosts?: Array<Host>;
  /**
   * A proxy URL to use for creating HTTP connections outside the cluster. http://\\<username\\>:\\<pswd\\>@\\<ip\\>:\\<port\\>
   */
  http_proxy?: string;
  /**
   * A proxy URL to use for creating HTTPS connections outside the cluster. http://\\<username\\>:\\<pswd\\>@\\<ip\\>:\\<port\\>
   */
  https_proxy?: string;
  /**
   * Enable/disable hyperthreading on master nodes, arbiter nodes, worker nodes, or a combination of them.
   */
  hyperthreading?: ClusterHyperthreadingEnum;
  ignition_endpoint?: IgnitionEndpoint;
  /**
   * Json formatted string containing a list of cluster validations to be ignored. May also contain a list with a single string \"all\" to ignore all cluster validations. Some validations cannot be ignored.
   */
  ignored_cluster_validations?: string;
  /**
   * Json formatted string containing a list of host validations to be ignored. May also contain a list with a single string \"all\" to ignore all host validations. Some validations cannot be ignored.
   */
  ignored_host_validations?: string;
  /**
   * Indicates whether this cluster is an imported day-2 cluster or a regular cluster. Clusters are considered imported when they are created via the ../clusters/import endpoint. Day-2 clusters converted from day-1 clusters by kube-api controllers or the ../clusters/<cluster_id>/actions/allow-add-hosts endpoint are not considered imported. Imported clusters usually lack a lot of information and are filled with default values that don\'t necessarily reflect the actual cluster they represent
   */
  imported?: boolean;
  /**
   * The virtual IPs used for cluster ingress traffic. Enter one IP address for single-stack clusters, or up to two for dual-stack clusters (at most one IP address per IP stack used). The order of stacks should be the same as order of subnets in Cluster Networks, Service Networks, and Machine Networks.
   */
  ingress_vips?: Array<IngressVip> | null;
  /**
   * The time that this cluster completed installation.
   */
  install_completed_at?: string;
  /**
   * JSON-formatted string containing the user overrides for the install-config.yaml file.
   */
  install_config_overrides?: string;
  /**
   * The time that this cluster started installation.
   */
  install_started_at?: string;
  /**
   * Json formatted string containing ip collisions detected in the cluster.
   */
  ip_collisions?: string;
  'last-installation-preparation'?: LastInstallationPreparation;
  load_balancer?: LoadBalancer;
  logs_info?: LogsState;
  /**
   * A CIDR that all hosts belonging to the cluster should have an interfaces with IP address that belongs to this CIDR. The api_vip belongs to this CIDR.
   */
  machine_network_cidr?: string;
  /**
   * Machine networks that are associated with this cluster.
   */
  machine_networks?: Array<MachineNetwork> | null;
  /**
   * Operators that are associated with this cluster.
   */
  monitored_operators?: Array<MonitoredOperator>;
  /**
   * Name of the OpenShift cluster.
   */
  name?: string;
  /**
   * The desired network type used. - OVNKubernetes: Default CNI for OpenShift (recommended) - OpenShiftSDN: Legacy SDN (deprecated in newer versions) - CiscoACI: Cisco ACI CNI (requires custom manifests) - Cilium: Isovalent Cilium CNI (requires custom manifests) - Calico: Tigera Calico CNI (requires custom manifests) - None: No CNI - user must provide custom CNI manifests
   */
  network_type?: ClusterNetworkTypeEnum | null;
  /**
   * A comma-separated list of destination domain names, domains, IP addresses, or other network CIDRs to exclude from proxying.
   */
  no_proxy?: string;
  /**
   * A comma-separated list of NTP sources (name or IP) to be used as the only NTP configuration for the cluster hosts.
   */
  ntp_sources?: string;
  /**
   * OpenShift release image URI.
   */
  ocp_release_image?: string;
  /**
   * Cluster ID on OCP system.
   */
  openshift_cluster_id?: string;
  /**
   * Version of the OpenShift cluster.
   */
  openshift_version?: string;
  /**
   * Bundles that were selected for this cluster, with the optional operators chosen by the user. Derived from monitored operators\' source_bundles. Not persisted directly.
   */
  operator_bundles?: Array<BundleCreateParams>;
  org_id?: string;
  /**
   * Indication if organization soft timeouts is enabled for the cluster.
   */
  org_soft_timeouts_enabled?: boolean;
  platform?: Platform;
  progress?: ClusterProgressInfo;
  /**
   * True if the pull secret has been added to the cluster.
   */
  pull_secret_set?: boolean;
  /**
   * hosts associated to this cluster that are in \'known\' state.
   */
  ready_host_count?: number;
  /**
   * Schedule workloads on masters
   */
  schedulable_masters?: boolean;
  /**
   * Indicates if schedule workloads on masters will be enabled regardless the value of \'schedulable_masters\' property. Set to \'true\' when not enough hosts are associated with this cluster to disable the scheduling on masters.
   */
  schedulable_masters_forced_true?: boolean;
  /**
   * The IP address pool to use for service IP addresses. You can enter only one IP address pool. If you need to access the services from an external network, configure load balancers and routers to manage the traffic.
   */
  service_network_cidr?: string;
  /**
   * Service networks that are associated with this cluster.
   */
  service_networks?: Array<ServiceNetwork> | null;
  /**
   * SSH public key for debugging OpenShift nodes.
   */
  ssh_public_key?: string;
  /**
   * The last time that the cluster status was updated.
   */
  status_updated_at?: string;
  /**
   * A comma-separated list of tags that are associated to the cluster.
   */
  tags?: string;
  /**
   * All hosts associated to this cluster.
   */
  total_host_count?: number;
  /**
   * The last time that this cluster was updated.
   */
  updated_at?: string;
  /**
   * (DEPRECATED) Indicate if the networking is managed by the user.
   */
  user_managed_networking?: boolean | null;
  user_name?: string;
  /**
   * JSON-formatted string containing the validation results for each validation id grouped by category (network, hosts-data, etc.)
   */
  validations_info?: string;
  /**
   * Indicate if virtual IP DHCP allocation mode is enabled.
   */
  vip_dhcp_allocation?: boolean | null;
}

export enum ClusterKindEnum {
  Cluster = 'Cluster',
  AddHostsCluster = 'AddHostsCluster',
  DisconnectedCluster = 'DisconnectedCluster',
}
export enum ClusterStatusEnum {
  Insufficient = 'insufficient',
  Ready = 'ready',
  Error = 'error',
  PreparingForInstallation = 'preparing-for-installation',
  PendingForInput = 'pending-for-input',
  Installing = 'installing',
  Finalizing = 'finalizing',
  Installed = 'installed',
  AddingHosts = 'adding-hosts',
  Cancelled = 'cancelled',
  InstallingPendingUserAction = 'installing-pending-user-action',
  Unmonitored = 'unmonitored',
}
export enum ClusterCpuArchitectureEnum {
  X8664 = 'x86_64',
  Aarch64 = 'aarch64',
  Arm64 = 'arm64',
  Ppc64le = 'ppc64le',
  S390x = 's390x',
  Multi = 'multi',
}
export enum ClusterHighAvailabilityModeEnum {
  Full = 'Full',
  None = 'None',
}
export enum ClusterHyperthreadingEnum {
  None = 'none',
  Masters = 'masters',
  Arbiters = 'arbiters',
  Workers = 'workers',
  Mastersarbiters = 'masters,arbiters',
  Mastersworkers = 'masters,workers',
  Arbitersworkers = 'arbiters,workers',
  Mastersarbitersworkers = 'masters,arbiters,workers',
  All = 'all',
}
export enum ClusterNetworkTypeEnum {
  OpenShiftSdn = 'OpenShiftSDN',
  OvnKubernetes = 'OVNKubernetes',
  CiscoAci = 'CiscoACI',
  Cilium = 'Cilium',
  Calico = 'Calico',
  None = 'None',
}
