/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ClusterHostRequirementsDetails } from './cluster-host-requirements-details';
// May contain unused imports in some cases
// @ts-ignore
import type { OperatorHostRequirements } from './operator-host-requirements';

export interface ClusterHostRequirements {
  /**
   * Unique identifier of the host the requirements relate to.
   */
  host_id?: string;
  ocp?: ClusterHostRequirementsDetails;
  /**
   * Host requirements related to requested operators
   */
  operators?: Array<OperatorHostRequirements>;
  total?: ClusterHostRequirementsDetails;
}
