/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Cpu
 */
export interface Cpu {
  /**
   *
   * @type {string}
   * @memberof Cpu
   */
  architecture?: string;
  /**
   *
   * @type {number}
   * @memberof Cpu
   */
  count?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof Cpu
   */
  flags?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof Cpu
   */
  frequency?: number;
  /**
   *
   * @type {string}
   * @memberof Cpu
   */
  model_name?: string;
}
