/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DiskInstallationEligibility } from './disk-installation-eligibility';
// May contain unused imports in some cases
// @ts-ignore
import type { DriveType } from './drive-type';
// May contain unused imports in some cases
// @ts-ignore
import type { IoPerf } from './io-perf';
// May contain unused imports in some cases
// @ts-ignore
import type { Iscsi } from './iscsi';

export interface Disk {
  bootable?: boolean;
  /**
   * by-id is the World Wide Number of the device which guaranteed to be unique for every storage device
   */
  by_id?: string;
  /**
   * by-path is the shortest physical path to the device
   */
  by_path?: string;
  drive_type?: DriveType;
  has_uuid?: boolean;
  hctl?: string;
  /**
   * A comma-separated list of disk names that this disk belongs to
   */
  holders?: string;
  /**
   * Determine the disk\'s unique identifier which is the by-id field if it exists and fallback to the by-path field otherwise
   */
  id?: string;
  installation_eligibility?: DiskInstallationEligibility;
  io_perf?: IoPerf;
  /**
   * Whether the disk appears to be an installation media or not
   */
  is_installation_media?: boolean;
  iscsi?: Iscsi;
  model?: string;
  name?: string;
  partitionTypes?: string;
  path?: string;
  removable?: boolean;
  serial?: string;
  size_bytes?: number;
  smart?: string;
  vendor?: string;
  wwn?: string;
}
