/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DiskEncryption {
  /**
   * Enable/disable disk encryption on master nodes, arbiter nodes, worker nodes, or a combination of them.
   */
  enable_on?: DiskEncryptionEnableOnEnum;
  /**
   * The disk encryption mode to use.
   */
  mode?: DiskEncryptionModeEnum;
  /**
   * JSON-formatted string containing additional information regarding tang\'s configuration
   */
  tang_servers?: string;
}

export enum DiskEncryptionEnableOnEnum {
  None = 'none',
  Masters = 'masters',
  Arbiters = 'arbiters',
  Workers = 'workers',
  Mastersarbiters = 'masters,arbiters',
  Mastersworkers = 'masters,workers',
  Arbitersworkers = 'arbiters,workers',
  Mastersarbitersworkers = 'masters,arbiters,workers',
  All = 'all',
}
export enum DiskEncryptionModeEnum {
  Tpmv2 = 'tpmv2',
  Tang = 'tang',
}
