/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DomainResolutionResponseResolutionsInner } from './domain-resolution-response-resolutions-inner';

/**
 *
 * @export
 * @interface DomainResolutionResponse
 */
export interface DomainResolutionResponse {
  /**
   *
   * @type {Array<DomainResolutionResponseResolutionsInner>}
   * @memberof DomainResolutionResponse
   */
  resolutions: Array<DomainResolutionResponseResolutionsInner>;
}
