/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */

export enum FeatureSupportLevelId {
  Sno = 'SNO',
  VipAutoAlloc = 'VIP_AUTO_ALLOC',
  CustomManifest = 'CUSTOM_MANIFEST',
  SingleNodeExpansion = 'SINGLE_NODE_EXPANSION',
  Lvm = 'LVM',
  Odf = 'ODF',
  Lso = 'LSO',
  Cnv = 'CNV',
  Mce = 'MCE',
  NutanixIntegration = 'NUTANIX_INTEGRATION',
  VsphereIntegration = 'VSPHERE_INTEGRATION',
  DualStackVips = 'DUAL_STACK_VIPS',
  ClusterManagedNetworking = 'CLUSTER_MANAGED_NETWORKING',
  UserManagedNetworking = 'USER_MANAGED_NETWORKING',
  MinimalIso = 'MINIMAL_ISO',
  FullIso = 'FULL_ISO',
  ExternalPlatformOci = 'EXTERNAL_PLATFORM_OCI',
  DualStack = 'DUAL_STACK',
}
