/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FencingCredentialsParams {
  /**
   * The URL of the host\'s BMC, for example https://bmc1.example.com.
   */
  address: string;
  /**
   * The password to connect to the host\'s BMC.
   */
  password: string;
  /**
   * The username to connect to the host\'s BMC.
   */
  username: string;
  /**
   * Whether to enable or disable certificate verification when connecting to the host\'s BMC.
   */
  certificate_verification?: FencingCredentialsParamsCertificateVerificationEnum;
}

export enum FencingCredentialsParamsCertificateVerificationEnum {
  Enabled = 'Enabled',
  Disabled = 'Disabled',
}
