/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Host } from './host';
// May contain unused imports in some cases
// @ts-ignore
import { HostProgressInfo } from './host-progress-info';
// May contain unused imports in some cases
// @ts-ignore
import { HostRegistrationResponseAllOfNextStepRunnerCommand } from './host-registration-response-all-of-next-step-runner-command';
// May contain unused imports in some cases
// @ts-ignore
import { HostRole } from './host-role';
// May contain unused imports in some cases
// @ts-ignore
import { HostStage } from './host-stage';
// May contain unused imports in some cases
// @ts-ignore
import { LogsState } from './logs-state';

/**
 * @type HostRegistrationResponse
 * @export
 */
export type HostRegistrationResponse = Host;
