/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DiskConfigParams } from './disk-config-params';
// May contain unused imports in some cases
// @ts-ignore
import { DiskSkipFormattingParams } from './disk-skip-formatting-params';
// May contain unused imports in some cases
// @ts-ignore
import { NodeLabelParams } from './node-label-params';

/**
 *
 * @export
 * @interface HostUpdateParams
 */
export interface HostUpdateParams {
  /**
   *
   * @type {Array<DiskConfigParams>}
   * @memberof HostUpdateParams
   */
  disks_selected_config?: Array<DiskConfigParams> | null;
  /**
   * Allows changing the host\'s skip_formatting_disks parameter
   * @type {Array<DiskSkipFormattingParams>}
   * @memberof HostUpdateParams
   */
  disks_skip_formatting?: Array<DiskSkipFormattingParams> | null;
  /**
   *
   * @type {string}
   * @memberof HostUpdateParams
   */
  host_name?: string | null;
  /**
   *
   * @type {string}
   * @memberof HostUpdateParams
   */
  host_role?: HostUpdateParamsHostRoleEnum;
  /**
   * A string which will be used as Authorization Bearer token to fetch the ignition from ignition_endpoint_url.
   * @type {string}
   * @memberof HostUpdateParams
   */
  ignition_endpoint_token?: string | null;
  /**
   *
   * @type {string}
   * @memberof HostUpdateParams
   */
  machine_config_pool_name?: string | null;
  /**
   * Labels to be added to the corresponding node.
   * @type {Array<NodeLabelParams>}
   * @memberof HostUpdateParams
   */
  node_labels?: Array<NodeLabelParams> | null;
}

/**
 * @export
 * @enum {string}
 */
export enum HostUpdateParamsHostRoleEnum {
  AutoAssign = 'auto-assign',
  Master = 'master',
  Worker = 'worker',
}
