/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Explicit ignition endpoint overrides the default ignition endpoint.
 * @export
 * @interface IgnitionEndpoint
 */
export interface IgnitionEndpoint {
  /**
   * base64 encoded CA certficate to be used when contacting the URL via https.
   * @type {string}
   * @memberof IgnitionEndpoint
   */
  ca_certificate?: string | null;
  /**
   * The URL for the ignition endpoint.
   * @type {string}
   * @memberof IgnitionEndpoint
   */
  url?: string | null;
}
