/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IgnitionEndpointHttpHeadersParams {
  /**
   * The key for the http header\'s key-value pair.
   */
  key: string;
  /**
   * The value for the http header\'s key-value pair.
   */
  value: string;
}
