/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ImageType } from './image-type';

export interface ImageInfo {
  created_at?: string;
  download_url?: string;
  expires_at?: string;
  /**
   * Image generator version.
   */
  generator_version?: string;
  size_bytes?: number;
  /**
   * SSH public key for debugging the installation.
   */
  ssh_public_key?: string;
  /**
   * static network configuration string in the format expected by discovery ignition generation
   */
  static_network_config?: string;
  type?: ImageType;
}
