/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ImportClusterParams {
  /**
   * The domain name used to reach the OpenShift cluster API.
   */
  api_vip_dnsname: string;
  /**
   * OpenShift cluster name.
   */
  name: string;
  /**
   * The id of the OCP cluster, that hosts will be added to
   */
  openshift_cluster_id: string;
  /**
   * Version of the OpenShift cluster.
   */
  openshift_version?: string;
}
