/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ImageType } from './image-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Proxy } from './proxy';

export interface InfraEnv {
  created_at: string;
  /**
   * Self link.
   */
  href: string;
  /**
   * Unique identifier of the object.
   */
  id: string;
  /**
   * Indicates the type of this object.
   */
  kind: InfraEnvKindEnum;
  /**
   * Name of the infra-env.
   */
  name: string;
  type: ImageType;
  /**
   * The last time that this infra-env was updated.
   */
  updated_at: string;
  /**
   * A comma-separated list of NTP sources (name or IP) going to be added to all the hosts.
   */
  additional_ntp_sources?: string;
  /**
   * PEM-encoded X.509 certificate bundle. Hosts discovered by this infra-env will trust the certificates in this bundle. Clusters formed from the hosts discovered by this infra-env will also trust the certificates in this bundle.
   */
  additional_trust_bundle?: string;
  /**
   * If set, all hosts that register will be associated with the specified cluster.
   */
  cluster_id?: string;
  /**
   * The CPU architecture of the image (x86_64/arm64/etc).
   */
  cpu_architecture?: InfraEnvCpuArchitectureEnum;
  download_url?: string;
  email_domain?: string;
  expires_at?: string;
  /**
   * Image generator version.
   */
  generator_version?: string;
  /**
   * Json formatted string containing the user overrides for the initial ignition config.
   */
  ignition_config_override?: string;
  /**
   * JSON formatted string array representing the discovery image kernel arguments.
   */
  kernel_arguments?: string | null;
  /**
   * The number of seconds to wait before mapping host MACs to interfaces when applying static network config on minimal ISO. This can be used on hosts that need time to discover their NICs.
   */
  network_discovery_delay_seconds?: number | null;
  /**
   * A comma-separated list of NTP sources (name or IP) to be used as the only NTP configuration for hosts in this infra-env.
   */
  ntp_sources?: string;
  /**
   * Version of the OpenShift cluster (used to infer the RHCOS version - temporary until generic logic implemented).
   */
  openshift_version?: string;
  org_id?: string;
  proxy?: Proxy;
  /**
   * True if the pull secret has been added to the cluster.
   */
  pull_secret_set?: boolean;
  /**
   * The IP address of the host that will act as the rendezvous (bootstrap) node for agent-based installations. This is optional for disconnected-iso image type and specifies which host will run the assisted service during the bootstrap phase. All other hosts will connect to this IP to coordinate the installation.
   */
  rendezvous_ip?: string | null;
  size_bytes?: number;
  /**
   * SSH public key for debugging the installation.
   */
  ssh_authorized_key?: string;
  /**
   * static network configuration string in the format expected by discovery ignition generation.
   */
  static_network_config?: string;
  user_name?: string;
}

export enum InfraEnvKindEnum {
  InfraEnv = 'InfraEnv',
}
export enum InfraEnvCpuArchitectureEnum {
  X8664 = 'x86_64',
  Aarch64 = 'aarch64',
  Arm64 = 'arm64',
  Ppc64le = 'ppc64le',
  S390x = 's390x',
}
