/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { VipVerification } from './vip-verification';

/**
 * The virtual IP used for cluster ingress traffic.
 * @export
 * @interface IngressVip
 */
export interface IngressVip {
  /**
   * The cluster that this VIP is associated with.
   * @type {string}
   * @memberof IngressVip
   */
  cluster_id?: string;
  /**
   *
   * @type {string}
   * @memberof IngressVip
   */
  ip?: string;
  /**
   *
   * @type {VipVerification}
   * @memberof IngressVip
   */
  verification?: VipVerification;
}
