/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InstallerArgsParams
 */
export interface InstallerArgsParams {
  /**
   * List of additional arguments passed to coreos-installer
   * @type {Array<string>}
   * @memberof InstallerArgsParams
   */
  args?: Array<string>;
}
