/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InventoryTruncation {
  type: InventoryTruncationTypeEnum;
  /**
   * Reasons for the truncation
   */
  reasons?: Array<string>;
}

export enum InventoryTruncationTypeEnum {
  Partial = 'partial',
  Full = 'full',
}
