/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Manifest
 */
export interface Manifest {
  /**
   * The file name prefaced by the folder that contains it.
   * @type {string}
   * @memberof Manifest
   */
  file_name?: string;
  /**
   * The folder that contains the files. Manifests can be placed in \'manifests\' or \'openshift\' directories.
   * @type {string}
   * @memberof Manifest
   */
  folder?: ManifestFolderEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ManifestFolderEnum {
  Manifests = 'manifests',
  Openshift = 'openshift',
}
