/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { FeatureSupportLevelId } from './feature-support-level-id';
// May contain unused imports in some cases
// @ts-ignore
import type { IncompatibilityReason } from './incompatibility-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { SupportLevel } from './support-level';

export interface Operator {
  dependencies: Array<FeatureSupportLevelId>;
  'feature-support-level-id': FeatureSupportLevelId;
  incompatibilities: Array<FeatureSupportLevelId>;
  /**
   * Name of the operator
   */
  name: string;
  support_level: SupportLevel;
  reason?: IncompatibilityReason;
}
