/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OperatorStatus } from './operator-status';

export interface OperatorMonitorReport {
  /**
   * Unique name of the operator.
   */
  name?: string;
  status?: OperatorStatus;
  /**
   * Detailed information about the operator state.
   */
  status_info?: string;
  /**
   * operator version.
   */
  version?: string;
}
