/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OperatorProperty {
  /**
   * Type of the property
   */
  data_type?: OperatorPropertyDataTypeEnum;
  /**
   * Default value for the property
   */
  default_value?: string;
  /**
   * Description of a property
   */
  description?: string;
  /**
   * Indicates whether the property is reqired
   */
  mandatory?: boolean;
  /**
   * Name of the property
   */
  name?: string;
  /**
   * Values to select from
   */
  options?: Array<string>;
}

export enum OperatorPropertyDataTypeEnum {
  Boolean = 'boolean',
  String = 'string',
  Integer = 'integer',
  Float = 'float',
}
