/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { OperatorStatus } from './operator-status';

/**
 *
 * @export
 * @interface OperatorMonitorReport
 */
export interface OperatorMonitorReport {
  /**
   * Unique name of the operator.
   * @type {string}
   * @memberof OperatorMonitorReport
   */
  name?: string;
  /**
   *
   * @type {OperatorStatus}
   * @memberof OperatorMonitorReport
   */
  status?: OperatorStatus;
  /**
   * Detailed information about the operator state.
   * @type {string}
   * @memberof OperatorMonitorReport
   */
  status_info?: string;
  /**
   * operator version.
   * @type {string}
   * @memberof OperatorMonitorReport
   */
  version?: string;
}
