/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { PlatformType } from './platform-type';

/**
 * The configuration for the specific platform upon which to perform the installation.
 * @export
 * @interface Platform
 */
export interface Platform {
  /**
   *
   * @type {PlatformType}
   * @memberof Platform
   */
  type: PlatformType;
  /**
   * Used by the service to indicate that the platform-specific components are not included in OpenShift and must be provided as manifests separately.
   * @type {boolean}
   * @memberof Platform
   */
  is_external?: boolean;
}
