/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Configuration used when installing with an external platform type.
 */
export interface PlatformExternal {
  /**
   * When set to external, this property will enable an external cloud provider.
   */
  cloud_controller_manager?: PlatformExternalCloudControllerManagerEnum | null;
  /**
   * Holds the arbitrary string representing the infrastructure provider name.
   */
  platform_name?: string | null;
}

export enum PlatformExternalCloudControllerManagerEnum {
  Empty = '',
  External = 'External',
}
