/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Information sent to the agent for rebooting a host into discovery.
 * @export
 * @interface RebootForReclaimRequest
 */
export interface RebootForReclaimRequest {
  /**
   * The base directory on the host that contains the /boot folder. The host needs to chroot into this directory in order to properly reboot.
   * @type {string}
   * @memberof RebootForReclaimRequest
   */
  host_fs_mount_dir: string;
}
