/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Route {
  /**
   * The destination network or destination host
   */
  destination?: string;
  /**
   * Defines whether this is an IPv4 (4) or IPv6 route (6)
   */
  family?: number;
  /**
   * Gateway address where the packets are sent
   */
  gateway?: string;
  /**
   * Interface to which packets for this route will be sent
   */
  interface?: string;
  /**
   * Route priority metric
   */
  metric?: number;
}
