/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * IP address block for service IP blocks.
 */
export interface ServiceNetwork {
  cidr?: string;
  /**
   * A network to use for service IP addresses. If you need to access the services from an external network, configure load balancers and routers to manage the traffic.
   */
  cluster_id?: string;
}
