/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SupportLevel } from './support-level';

/**
 * Map of feature ID or CPU architecture alongside their support level
 * @export
 * @interface SupportLevels
 */
export interface SupportLevels {
  [key: string]: SupportLevel;
}
