/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { TangConnectivityResponseTangServerResponseInner } from './tang-connectivity-response-tang-server-response-inner';

export interface TangConnectivityResponse {
  /**
   * Tang check result.
   */
  is_success?: boolean;
  tang_server_response?: Array<TangConnectivityResponseTangServerResponseInner>;
}
