/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { TangConnectivityResponseTangServerResponseInnerSignaturesInner } from './tang-connectivity-response-tang-server-response-inner-signatures-inner';

export interface TangConnectivityResponseTangServerResponseInner {
  /**
   * Tang response payload.
   */
  payload?: string;
  signatures?: Array<TangConnectivityResponseTangServerResponseInnerSignaturesInner>;
  /**
   * Tang URL.
   */
  tang_url?: string;
}
