/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateManifestParams {
  /**
   * The file name for the manifest to modify.
   */
  file_name: string;
  /**
   * The folder for the manifest to modify.
   */
  folder: UpdateManifestParamsFolderEnum;
  /**
   * The new base64 encoded manifest content.
   */
  updated_content?: string | null;
  /**
   * The new file name for the manifest.
   */
  updated_file_name?: string | null;
  /**
   * The new folder for the manifest. Manifests can be placed in \'manifests\' or \'openshift\' directories.
   */
  updated_folder?: UpdateManifestParamsUpdatedFolderEnum | null;
}

export enum UpdateManifestParamsFolderEnum {
  Manifests = 'manifests',
  Openshift = 'openshift',
}
export enum UpdateManifestParamsUpdatedFolderEnum {
  Manifests = 'manifests',
  Openshift = 'openshift',
}
