/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Usage {
  /**
   * additional properties of the feature
   */
  data?: { [key: string]: object };
  /**
   * Unique idenftifier of the feature
   */
  id?: string;
  /**
   * name of the feature to track
   */
  name?: string;
}
