/* tslint:disable */
/* eslint-disable */
/**
 * AssistedInstall
 * Assisted installation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { VersionedClusterHostRequirementsDetails } from './versioned-cluster-host-requirements-details';

export interface VersionedHostRequirements {
  arbiter?: VersionedClusterHostRequirementsDetails;
  'edge-worker'?: VersionedClusterHostRequirementsDetails;
  master?: VersionedClusterHostRequirementsDetails;
  /**
   * Determines how the version field is matched. \"exact\" applies only to the specified version (default). \"min_version\" applies to the specified version and all later versions.
   */
  match_type?: VersionedHostRequirementsMatchTypeEnum;
  sno?: VersionedClusterHostRequirementsDetails;
  /**
   * Version of the component for which requirements are defined
   */
  version?: string;
  worker?: VersionedClusterHostRequirementsDetails;
}

export enum VersionedHostRequirementsMatchTypeEnum {
  Exact = 'exact',
  MinVersion = 'min_version',
}
