/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ObjectReference
 */
export interface ObjectReference {
  /**
   *
   * @type {string}
   * @memberof ObjectReference
   */
  href?: string;
  /**
   *
   * @type {string}
   * @memberof ObjectReference
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ObjectReference
   */
  kind?: string;
}
