/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RegistryRequest
 */
export interface RegistryRequest {
  /**
   *
   * @type {boolean}
   * @memberof RegistryRequest
   */
  cloudAlias?: boolean;
  /**
   *
   * @type {string}
   * @memberof RegistryRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof RegistryRequest
   */
  org_name?: string;
  /**
   *
   * @type {string}
   * @memberof RegistryRequest
   */
  team_name?: string;
  /**
   *
   * @type {string}
   * @memberof RegistryRequest
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof RegistryRequest
   */
  url?: string;
}
