/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RegistryCredentialPatchRequest
 */
export interface RegistryCredentialPatchRequest {
  /**
   *
   * @type {string}
   * @memberof RegistryCredentialPatchRequest
   */
  account_id?: string;
  /**
   *
   * @type {string}
   * @memberof RegistryCredentialPatchRequest
   */
  external_resource_id?: string;
  /**
   *
   * @type {string}
   * @memberof RegistryCredentialPatchRequest
   */
  registry_id?: string;
  /**
   *
   * @type {string}
   * @memberof RegistryCredentialPatchRequest
   */
  token?: string;
  /**
   *
   * @type {string}
   * @memberof RegistryCredentialPatchRequest
   */
  username?: string;
}
