/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SubscriptionRoleBindingCreateRequest
 */
export interface SubscriptionRoleBindingCreateRequest {
  /**
   *
   * @type {string}
   * @memberof SubscriptionRoleBindingCreateRequest
   */
  account_username: string;
  /**
   *
   * @type {string}
   * @memberof SubscriptionRoleBindingCreateRequest
   */
  role_id: string;
}
