/* tslint:disable */
/* eslint-disable */
/**
 * Authorization Service API
 * Enables access control on resources of OCM services
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ErrorAllOf } from './error-all-of';
// May contain unused imports in some cases
// @ts-ignore
import type { ObjectReference } from './object-reference';

/**
 * @type ModelError
 */
export type ModelError = ErrorAllOf & ObjectReference;
