/* tslint:disable */
/* eslint-disable */
/**
 * Authorization Service API
 * Enables access control on resources of OCM services
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ResourceReview {
  account_username: string;
  action: ResourceReviewActionEnum;
  cluster_ids: Array<string>;
  cluster_uuids: Array<string>;
  organization_ids: Array<string>;
  resource_type: ResourceReviewResourceTypeEnum;
  subscription_ids: Array<string>;
}

export enum ResourceReviewActionEnum {
  Get = 'get',
  List = 'list',
  Create = 'create',
  Delete = 'delete',
  Update = 'update',
}
export enum ResourceReviewResourceTypeEnum {
  Cluster = 'Cluster',
  Subscription = 'Subscription',
}
