FROM registry.access.redhat.com/ubi9/nodejs-18-minimal:latest as ui-build
USER root
RUN microdnf install -y rsync git

WORKDIR /app
COPY --chown=1001:0 / /app
RUN ls /app
ENV NODE_OPTIONS='--max-old-space-size=8192'
RUN git config --global --add safe.directory /app
RUN npm install -g corepack@0.24.1
RUN yarn install --immutable && yarn build:all

FROM registry.access.redhat.com/ubi9/go-toolset:1.21 as proxy-build
WORKDIR /app
COPY apps/assisted-disconnected-ui/proxy /app
USER 0
RUN go build

FROM registry.access.redhat.com/ubi9/ubi-micro
COPY --from=ui-build /app/apps/assisted-disconnected-ui/build /app/proxy/dist
COPY --from=proxy-build /app/assisted-disconnected-ui /app/proxy
WORKDIR /app/proxy
EXPOSE 8080
CMD ./assisted-disconnected-ui
