/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccessReviewResponse {
  allowed: boolean;
  account_id?: string;
  action?: AccessReviewResponseActionEnum;
  cluster_id?: string;
  cluster_uuid?: string;
  is_ocm_internal?: boolean;
  organization_id?: string;
  reason?: string;
  resource_type?: AccessReviewResponseResourceTypeEnum;
  subscription_id?: string;
}

export enum AccessReviewResponseActionEnum {
  Get = 'get',
  List = 'list',
  Create = 'create',
  Delete = 'delete',
  Update = 'update',
}
export enum AccessReviewResponseResourceTypeEnum {
  AddOn = 'AddOn',
  Flavour = 'Flavour',
  Account = 'Account',
  AccountPool = 'AccountPool',
  Cluster = 'Cluster',
  Plan = 'Plan',
  Subscription = 'Subscription',
  Organization = 'Organization',
  Role = 'Role',
  Permission = 'Permission',
  RoleBinding = 'RoleBinding',
  Registry = 'Registry',
  RegistryCredential = 'RegistryCredential',
  CurrentAccount = 'CurrentAccount',
  AccessReview = 'AccessReview',
  SelfAccessReview = 'SelfAccessReview',
  ResourceReview = 'ResourceReview',
  SelfResourceReview = 'SelfResourceReview',
  ClusterRegistration = 'ClusterRegistration',
  AccessToken = 'AccessToken',
  ClusterAuthorization = 'ClusterAuthorization',
  SelfManagedCluster = 'SelfManagedCluster',
  RedhatManagedCluster = 'RedhatManagedCluster',
  ExportControlReview = 'ExportControlReview',
  ClusterLog = 'ClusterLog',
  ClusterCredential = 'ClusterCredential',
  ClusterMetric = 'ClusterMetric',
  ResourceQuota = 'ResourceQuota',
  ReservedResource = 'ReservedResource',
  Dashboard = 'Dashboard',
  ClusterProviderAndRegion = 'ClusterProviderAndRegion',
  ServiceLog = 'ServiceLog',
  InternalServiceLog = 'InternalServiceLog',
  CsLogs = 'CSLogs',
  SubscriptionLabel = 'SubscriptionLabel',
  OrganizationLabel = 'OrganizationLabel',
  SubscriptionLabelInternal = 'SubscriptionLabelInternal',
  SubscriptionInternal = 'SubscriptionInternal',
  SubscriptionRoleBinding = 'SubscriptionRoleBinding',
  ClusterSelfManaged = 'ClusterSelfManaged',
  ClusterSelfManagedAddon = 'ClusterSelfManagedAddon',
  ClusterSelfManagedLabel = 'ClusterSelfManagedLabel',
  ClusterSelfManagedStatus = 'ClusterSelfManagedStatus',
  OsdTrialProtectedCluster = 'OsdTrialProtectedCluster',
  ManifestWorkSync = 'ManifestWorkSync',
  ClusterForcedUpgrade = 'ClusterForcedUpgrade',
  DeleteProtection = 'DeleteProtection',
  ScheduledUpgrade = 'ScheduledUpgrade',
}
