/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AccountPatchRequest
 */
export interface AccountPatchRequest {
  /**
   *
   * @type {string}
   * @memberof AccountPatchRequest
   */
  ban_code?: string;
  /**
   *
   * @type {string}
   * @memberof AccountPatchRequest
   */
  ban_description?: string;
  /**
   *
   * @type {boolean}
   * @memberof AccountPatchRequest
   */
  banned?: boolean;
  /**
   *
   * @type {string}
   * @memberof AccountPatchRequest
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof AccountPatchRequest
   */
  first_name?: string;
  /**
   *
   * @type {string}
   * @memberof AccountPatchRequest
   */
  last_name?: string;
  /**
   *
   * @type {string}
   * @memberof AccountPatchRequest
   */
  organization_id?: string;
  /**
   *
   * @type {boolean}
   * @memberof AccountPatchRequest
   */
  service_account?: boolean;
}
