/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccountPatchRequest {
  ban_code?: string;
  ban_description?: string;
  banned?: boolean;
  email?: string;
  first_name?: string;
  last_name?: string;
  organization_id?: string;
  service_account?: boolean;
}
