/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CertificateSerial
 */
export interface CertificateSerial {
  /**
   *
   * @type {string}
   * @memberof CertificateSerial
   */
  created: string;
  /**
   *
   * @type {string}
   * @memberof CertificateSerial
   */
  expiration: string;
  /**
   *
   * @type {number}
   * @memberof CertificateSerial
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof CertificateSerial
   */
  serial: number;
  /**
   *
   * @type {string}
   * @memberof CertificateSerial
   */
  updated: string;
}
