/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ClusterMetricsNodes
 */
export interface ClusterMetricsNodes {
  /**
   *
   * @type {string}
   * @memberof ClusterMetricsNodes
   */
  arch?: string;
  /**
   *
   * @type {number}
   * @memberof ClusterMetricsNodes
   */
  compute?: number;
  /**
   *
   * @type {number}
   * @memberof ClusterMetricsNodes
   */
  infra?: number;
  /**
   *
   * @type {number}
   * @memberof ClusterMetricsNodes
   */
  master?: number;
  /**
   *
   * @type {number}
   * @memberof ClusterMetricsNodes
   */
  total?: number;
}
