/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ClusterTransferRequest {
  cluster_uuid?: string;
  owner?: string;
  recipient?: string;
  recipient_ebs_account_id?: string;
  recipient_external_org_id?: string;
}
