/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ClusterRegistrationResponse {
  account_id?: string;
  authorization_token?: string;
  cluster_id?: string;
  /**
   * Cluster Registration expiration in Unix time
   */
  expires_at?: string;
}
