/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ReservedResource } from './reserved-resource';

export interface ClusterAuthorizationRequest {
  account_username: string;
  cluster_id: string;
  availability_zone?: string;
  byoc?: boolean;
  cloud_account_id?: string;
  cloud_provider_id?: string;
  disconnected?: boolean;
  display_name?: string;
  external_cluster_id?: string;
  managed?: boolean;
  product_category?: ClusterAuthorizationRequestProductCategoryEnum;
  product_id?: ClusterAuthorizationRequestProductIdEnum;
  quota_version?: string;
  reserve?: boolean;
  resources?: Array<ReservedResource>;
  rh_region_id?: string;
  scope?: string;
}

export enum ClusterAuthorizationRequestProductCategoryEnum {
  AssistedInstall = 'assistedInstall',
  HostedControlPlane = 'HostedControlPlane',
}
export enum ClusterAuthorizationRequestProductIdEnum {
  Ocp = 'OCP',
  Osd = 'OSD',
  OsdTrial = 'OSDTrial',
  Moa = 'MOA',
  MoaHostedControlPlane = 'MOA-HostedControlPlane',
  Rhmi = 'RHMI',
  Rhosak = 'RHOSAK',
  RhosakTrial = 'RHOSAKTrial',
  Rhosr = 'RHOSR',
  RhosrTrial = 'RHOSRTrial',
  Rhose = 'RHOSE',
  RhoseTrial = 'RHOSETrial',
  Rhacs = 'RHACS',
  RhacsTrial = 'RHACSTrial',
  Aro = 'ARO',
  Rhoic = 'RHOIC',
  OcpAssistedInstall = 'OCP-AssistedInstall',
  Rovs = 'ROVS',
}
