/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EphemeralResourceQuota {
  availability_zone_type?: string;
  byoc?: boolean;
  resource_name?: string;
  resource_type?: string;
  sku?: string;
  sku_count?: number;
}
