/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface NotifyDetailsRequest {
  bcc_address?: string;
  cluster_id?: string;
  cluster_uuid?: string;
  include_red_hat_associates?: boolean;
  /**
   * The `internal_only` parameter is used for validation. Specifically to check if there is a discrepancy between the email address and the log type.
   */
  internal_only?: boolean;
  /**
   * The type of log for which the returned contacts will be used to send a notification. When informed it might influence the returned contacts.
   */
  log_type?: NotifyDetailsRequestLogTypeEnum;
  org_id?: string;
  subject?: string;
  subscription_id?: string;
}

export enum NotifyDetailsRequestLogTypeEnum {
  ClustercreateHighLevel = 'clustercreate-high-level',
  ClustercreateDetails = 'clustercreate-details',
  ClusterremoveHighLevel = 'clusterremove-high-level',
  ClusterremoveDetails = 'clusterremove-details',
  ClusterStateUpdates = 'cluster-state-updates',
  ClusterSubscription = 'Cluster Subscription',
  ClusterLifecycle = 'Cluster Lifecycle',
  ClusterUpdates = 'Cluster Updates',
  ClusterOwnership = 'Cluster Ownership',
  ClusterAccess = 'Cluster Access',
  ClusterScaling = 'Cluster Scaling',
  CapacityManagement = 'Capacity Management',
  ClusterConfiguration = 'Cluster Configuration',
  ClusterSecurity = 'Cluster Security',
  ClusterAddOns = 'Cluster Add-ons',
  CustomerSupport = 'Customer Support',
  ClusterNetworking = 'Cluster Networking',
  GeneralNotification = 'General Notification',
  ClusterTransferRecipient = 'cluster-transfer-recipient',
}
