/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ClusterMetricsNodes } from './cluster-metrics-nodes';
// May contain unused imports in some cases
// @ts-ignore
import type { ClusterResource } from './cluster-resource';
// May contain unused imports in some cases
// @ts-ignore
import type { ClusterUpgrade } from './cluster-upgrade';

export interface OneMetric {
  cloud_provider: string;
  cluster_type: string;
  compute_nodes_cpu: ClusterResource;
  compute_nodes_memory: ClusterResource;
  compute_nodes_sockets: ClusterResource;
  console_url: string;
  cpu: ClusterResource;
  critical_alerts_firing: number;
  memory: ClusterResource;
  nodes: ClusterMetricsNodes;
  non_virt_nodes: number;
  openshift_version: string;
  operating_system: string;
  operators_condition_failing: number;
  region: string;
  sockets: ClusterResource;
  state: string;
  state_description: string;
  storage: ClusterResource;
  subscription_cpu_total: number;
  subscription_obligation_exists: number;
  subscription_socket_total: number;
  upgrade: ClusterUpgrade;
  arch?: string;
  channel_info?: string;
  health_state?: OneMetricHealthStateEnum;
  nodes_arch?: Array<ClusterMetricsNodes>;
  query_timestamp?: string;
}

export enum OneMetricHealthStateEnum {
  Healthy = 'healthy',
  Unhealthy = 'unhealthy',
  Unknown = 'unknown',
}
