/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ExcessResource } from './excess-resource';
// May contain unused imports in some cases
// @ts-ignore
import { ObjectReference } from './object-reference';

/**
 *
 * @export
 * @interface QuotaAuthorizationResponse
 */
export interface QuotaAuthorizationResponse {
  /**
   *
   * @type {boolean}
   * @memberof QuotaAuthorizationResponse
   */
  allowed: boolean;
  /**
   *
   * @type {Array<ExcessResource>}
   * @memberof QuotaAuthorizationResponse
   */
  excess_resources: Array<ExcessResource>;
  /**
   *
   * @type {string}
   * @memberof QuotaAuthorizationResponse
   */
  organization_id?: string;
  /**
   *
   * @type {ObjectReference}
   * @memberof QuotaAuthorizationResponse
   */
  subscription?: ObjectReference;
}
