/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ReservedResourcePatchRequest {
  billing_model?: ReservedResourcePatchRequestBillingModelEnum;
  scope?: string;
}

export enum ReservedResourcePatchRequestBillingModelEnum {
  Standard = 'standard',
  Marketplace = 'marketplace',
  MarketplaceAws = 'marketplace-aws',
  MarketplaceRhm = 'marketplace-rhm',
  MarketplaceAzure = 'marketplace-azure',
  MarketplaceGcp = 'marketplace-gcp',
}
