/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { LandingPageCTLItem } from './landing-page-ctlitem';

/**
 *
 * @export
 * @interface SelfServiceLandingPageSchemaConfigTryLearn
 */
export interface SelfServiceLandingPageSchemaConfigTryLearn {
  /**
   *
   * @type {Array<LandingPageCTLItem>}
   * @memberof SelfServiceLandingPageSchemaConfigTryLearn
   */
  configure?: Array<LandingPageCTLItem>;
  /**
   *
   * @type {Array<LandingPageCTLItem>}
   * @memberof SelfServiceLandingPageSchemaConfigTryLearn
   */
  try?: Array<LandingPageCTLItem>;
}
