/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SelfServiceLandingPageSchemaConfigTryLearn } from './self-service-landing-page-schema-config-try-learn';
// May contain unused imports in some cases
// @ts-ignore
import type { SelfServiceLandingPageSchemaEstate } from './self-service-landing-page-schema-estate';

export interface SelfServiceLandingPageSchema {
  configTryLearn?: SelfServiceLandingPageSchemaConfigTryLearn;
  estate?: SelfServiceLandingPageSchemaEstate;
}
