/* tslint:disable */
/* eslint-disable */
/**
 * Account Management Service API
 * Manage user subscriptions and clusters
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SelfResourceReviewRequest
 */
export interface SelfResourceReviewRequest {
  /**
   *
   * @type {string}
   * @memberof SelfResourceReviewRequest
   */
  action?: SelfResourceReviewRequestActionEnum;
  /**
   *
   * @type {string}
   * @memberof SelfResourceReviewRequest
   */
  resource_type?: SelfResourceReviewRequestResourceTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum SelfResourceReviewRequestActionEnum {
  Get = 'get',
  Delete = 'delete',
  Update = 'update',
}
/**
 * @export
 * @enum {string}
 */
export enum SelfResourceReviewRequestResourceTypeEnum {
  Cluster = 'Cluster',
  Subscription = 'Subscription',
}
