FROM registry.access.redhat.com/ubi9/nodejs-22-minimal:latest AS builder
USER root
RUN microdnf install -y rsync git

WORKDIR /app
COPY --chown=1001:0 / /app
ENV NODE_OPTIONS='--max-old-space-size=8192'
RUN git config --global --add safe.directory /app
RUN npm install -g corepack@0.24.1
RUN yarn install --immutable && yarn build:all

FROM registry.access.redhat.com/ubi9/nodejs-22-minimal:latest AS runtime
USER root
RUN npm install -g serve
RUN mkdir -p /app/apps/assisted-installer-ui-chatbot
COPY --from=builder --chown=1001:0 /app/apps/assisted-chatbot/dist/ /app/apps/assisted-installer-ui-chatbot/
RUN chown -R 1001:0 /app
USER 1001

EXPOSE 8080
CMD ["serve", "/app", "-l", "8080"]
