name: Test and build on pull-request or push to specific branches

on:
  push:
    branches:
      - master
      - main
      - develop
      - feature/*
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - master
      - main
      - develop
      - release/*
      - hotfix/*

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '>=12.16'
          cache: yarn
      - name: Installing dependencies
        # --silent: Run yarn install without printing installation log.
        # --non-interactive: disable interactive prompts, like when there’s an invalid version of a dependency.
        # --pure-lockfile: doesn't generate a yarn.lock file.
        run: yarn install --silent --non-interactive --pure-lockfile
      - name: Checking for cyclic dependencies
        run: yarn test:circular
      - name: Typechecking
        run: yarn test:type-check
      - name: Linting
        run: yarn test:lint
      - name: Testing
        run: yarn test:ci
      - name: Building
        run: yarn build
