name: Test and build on push or pull request to specific branches

on:
  push:
    branches:
      - master
      - releases/*
      - CIM-*
  pull_request:
    branches:
      - master
      - releases/*
      - CIM-*

jobs:
  main:
    name: Test and build
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '>=12.16'
      - name: Install dependencies
        # --frozen-lockfile: doesn't generate a yarn.lock file, fails if an upate is needed.
        run: yarn install --frozen-lockfile
      - name: Build code (includes tests)
        run: yarn build
