name: Test and build on push or pull request to specific branches

on:
  push:
    branches:
      - master
      - main
      - develop
      - releases/*
      - CIM-*
  pull_request:
    branches:
      - master
      - main
      - develop
      - releases/*
      - CIM-*

jobs:
  main:
    name: Test and build
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '>=12.16'
          cache: yarn
      - name: Install dependencies
        # --slient: Run yarn install without printing installation log.
        # --non-interactive: disable interactive prompts, like when there’s an invalid version of a dependency.
        # --pure-lockfile: doesn't generate a yarn.lock file.
        run: yarn install --silent --non-interactive --pure-lockfile
      - name: Build code (includes tests)
        run: yarn build
